### ISSUE TITLE
Question: Delay until the main Window is loaded

### ISSUE THREAD

**Issue by charlesember** [Healix/Gw2Launcher#101]
Hello There,

I am just getting further into coding and am happy to be using you program. So first of all, thank you for making it ^^

Secondly i have a question. 
How do you determine when the main window is loaded? (Settings-General-Launching-Delay until main window is loaded)
I am wondering how you are doing this, since you'd have to work with the gw2 exe to figure that out.
And i currently dont know any way to catch those flags in other codes :/
Since i dont have any idea what to look for i thought id ask here.

Sorry for the inconvenience
Charly

**Comment by Healix** [comment]
First check if the game has been started by looking for a window with the class name "ArenaNet_Gr_Window_Class" (DX11) or "ArenaNet_Dx_Window_Class" (DX9). To check if it's loaded, I look at what has been loaded. For simplicity, you only need to check if "icm32.dll" or "mscms.dll" has been loaded by GW2.

The code for this is [WatchWindow()](https://github.com/Healix/Gw2Launcher/blob/master/Gw2Launcher/Client/Launcher_WindowWatcher.cs#L778).

If you'd rather know if a character is being played, simply check the [MumbleLink](https://wiki.guildwars2.com/wiki/API:MumbleLink) memory.

**Comment by charlesember** [comment]
Thank you for the quick answer ^^
