### ISSUE TITLE
Add options to exclude gw2.dat from full localized execution

### ISSUE THREAD

**Issue by samulisoderlund** [Healix/Gw2Launcher#112]
Copying a 50+ GB file for each account is a bit excessive.
Would it be possible to add an option to sync gw2.dat as a symbolic link instead of a copy?

**Comment by Healix** [comment]
It's a hard link - multiple paths given to the same file. It's not actually using any disk space.

**Comment by samulisoderlund** [comment]
Never mind this issue then 😄
