### ISSUE TITLE
Backup important account data

### ISSUE THREAD

**Issue by M6D6M6A** [Healix/Gw2Launcher#114]
Hello, is it possible to save all important account data (login data, auth key, ...) in case something happens to my laptop where everything is saved right now?

**Comment by M6D6M6A** [comment]
Is it just the "C:\Users\...\AppData\Roaming\Gw2Launcher\settings.dat" file? When I looked at the .dat in hex editor I could see all my emails and I think the auth keys too, is that where all the important data is stored?

**Comment by Healix** [comment]
Yes, settings.dat is the main file you'd want. Passwords stored by Gw2Launcher are encrypted to your user account by default, so if don't want to lose passwords, you'll want to change it under Settings > Security. If the login is stored by GW2, then it's located in the Local.dat file for the account, which can be found under the data folder.

If you want to create a full backup, copy everything except the data folder. For the data folder, only copy the files directly inside. There's also the default Local.dat and GFXSettings.xml file under %appdata%/Guild Wars 2/, if you're using them.

If you just want the account information, the [beta version](https://github.com/Healix/Gw2Launcher/blob/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe) has a preview for exporting accounts in CSV format (Settings > Tools).

**Comment by M6D6M6A** [comment]
Thank you, I have changed the settings.dat as described above to have the passwords in plain text and have saved the accounts as .csv and backupt, exactly the function I was looking for :)
