### ISSUE TITLE
DPI Scaling comes back on every day

### ISSUE THREAD

**Issue by MikSki17** [Healix/Gw2Launcher#116]
I have tried adjusting other options that require map change, then changing maps, nothing works. Maybe I'm just dumb and can't work out the options but the first 2 accounts I log in to, have no problem with that. The rest resets every day and I need to turn of DPI scaling which is very annoying. 
Management options I use:
Mode - Virtual
Localized execution - enabled (binaries, all addons)
What am I doing wrong?

**Comment by Healix** [comment]
GW2 will not save changes to any "local" settings when it allows multiple clients to be started. To have it save, launch by right clicking the account > selected > launch (normal).

**Comment by MikSki17** [comment]
That works now, thank you very much.
