### ISSUE TITLE
Second Monitor use for other accounts?

### ISSUE THREAD

**Issue by SalvorinFex** [Healix/Gw2Launcher#123]
I recently setup a second monitor on my system and was wondering if I can just, somehow "move" some account windows to it OR if I need to recreate them to utilize the second one during account setup?

**Comment by Healix** [comment]
Right click the account > Edit > Launch options. Windowed mode is near the top. Click the "..." button and move the window where you want it. You can also right click the window and choose to show other accounts if you want to move others at the same time.

If you were wanting full screen on multiple screens, GW2 doesn't support that. However, there's a "bug" with the DX11 version where you can launch in windowed mode, place the window on the screen you want, then press ALT+Enter to fill the screen it's currently on.

**Comment by SalvorinFex** [comment]
Awesome, Thanks so much for this Great tool!!
