### ISSUE TITLE
Feature request: Easier page navigation

### ISSUE THREAD

**Issue by samulisoderlund** [Healix/Gw2Launcher#126]
I have my accounts organized across multiple pages, but I feel navigation between the pages is a bit tedious.
My suggestion for improvement is threefold.

1. Add an option to show page navigation in the top bar, much like the start/stop button.
2. Let me type the number of the page I want to navigate to.
3. Add key shortcuts (e.g. left and right arrow keys) to navigate to previous and next pages.

**Comment by samulisoderlund** [comment]
I did not know about the scroll wheel. That already makes things easier. Typing the page number while the menu is open works too. What do you think about the arrow keys? I would be neat if I didn't have to click anything.

**Comment by Healix** [comment]
Adding arrow keys is simple - it's just adding an extra key to an existing function.
