### ISSUE TITLE
every time i reboot windows i need to resync because failed launch

### ISSUE THREAD

**Issue by anywayaura** [Healix/Gw2Launcher#127]
fail hover: "object reference does not point to an instance of an object" 

pls help. 

settings
https://i.imgur.com/2Y6D7Tk.png

actually, i tried to reboot with every combination of checkbox on this. always fail.
but not only resync helps. every touching localized exec or localized coherentui checkboxes also help run after

even button "open folder" helps

**Comment by Healix** [comment]
Use the [beta version](https://github.com/Healix/Gw2Launcher/tree/master/Gw2Launcher/bin64/Beta). There's a bug in the release version that causes that error if you use the -dx9/-dx11 option while leaving the launch arguments (under settings) empty. If this is the cause, you should see the error whenever you restart Gw2Launcher and opening the settings and simply clicking OK will fix it.

**Comment by auraanyway** [comment]
thank you very much! i really had -dx11 parameter on every account. <3
