### ISSUE TITLE
Opens game updates URL once a second instead of autolaunching the game

### ISSUE THREAD

**Issue by Iiridayn** [Healix/Gw2Launcher#134]
Started after rebooted to install the last big windows 10 update. I've delayed it for a few weeks, so it's not recent. Surprised no bug report - might be something specific to my environment. Happy to help reproduce.

Windows 10, MS Surface Pro 5, 21H2, latest critical updates.

**Comment by Healix** [comment]
Where it clicks is automatically calculated based on the size of GW2's window, so if it's wrong, the reported window size was likely wrong.

To manually configure it:

Right click any account > Selected > Disable automatic logins. Launch any account and leave it on the launcher. Right click any account > Edit > Launch options. Click the >> next to automatically login to character select. Check the box for the play button, then click and drag the + to the center of the play button on the launcher - the coordinate should update when you release it. OK out of the settings to save it.
