### ISSUE TITLE
Can't switch security methods - resolved.

### ISSUE THREAD

**Issue by stevenarm** [Healix/Gw2Launcher#138]
I am trying to move the configuration to another device.  I am changing the encryption from user to portable.  When I do so it asks for the password for my current user account.  I can't get past that point.  I am running windows 10 and I my account setup on the PC is microsoft account (not a local account) and is set up with a pin number.  Neither the pin nor the password for the account works to allow me to change the security settings.  I've also noticed that the account that pops up is an alias email not my actual microsoft account.  

Is there a way to correct this?

**Comment by Healix** [comment]
It's wanting the password for the specified GW2 account. It's the oldest email/password you entered under the account's setting in Gw2Launcher.

**Comment by stevenarm** [comment]
> It's wanting the password for the specified GW2 account. It's the oldest email/password you entered under the account's setting in Gw2Launcher.

Thanks!  So obvious now.  The fact that my microsoft and arenanet account were almost the same tripped me up.

**Comment by stevenarm** [comment]
User error.  Thanks for the help resolving.
