### ISSUE TITLE
[Request]  Mass update .dat files?

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [Healix/Gw2Launcher#14]
So I have a bunch of accounts stored in their own folder as files like 1.dat, 2.dat, etc.  Is there a way to have GW2Launcher mass update them 1 after another, instead of manually going into a folder and selecting them 1 by 1?  Like to have GW2Launcher select the folder and run an update on all the files keeping the same file names.

**Comment by Healix** [comment]
To clarify, you want to use Gw2Launcher to update various Local.dat files that are unrelated to Gw2Launcher? I'm assuming you want to use Gw2Launcher's asset server tools?

**Comment by SaiyanOfDarkness** [comment]
So basically I have a set of .dat files in a folder and have those saved and use symlinks when I want to switch accounts.  While using Handle to kill off the mutex.  However GW2Launcher seems to be one of the only apps that I know that can successfully update the .dat file without getting the "download failed" error.  The problem is I have to manually go in and browse each .dat file 1 by 1 and update it.  So was looking for a way for it to select a folder instead and just run the update on each file 1 after another while keeping the respective file names in the same folder they came from.  So basically it would take 1.dat, copy it to a temporary location, run the update on it, then move it back and replace the old one, then move onto 2.dat.. and so on.

**Comment by Healix** [comment]
The "download failed" occurs when you attempt to launch GW2 with -sharearchive while Gw2.dat is patched but Local.dat is not.

It's an odd choice to use Gw2Launcher solely to update, especially like that. You could create however many accounts in Gw2Launcher, choosing to create  a new Local.dat file for each one, then manually go into the folder where they're all stored (%appdata%\\Gw2Launcher\\data\\) and replace them with links to your own files.

If you just want to update all of your accounts however, why not use the same method you're already using? Simply replace "Gw2.exe -sharearchive" with "Gw2.exe -image". Something like this:

update.bat:
del "%appdata%\\Guild Wars 2\\Local.dat"
mklink /H "%appdata%\\Guild Wars 2\\Local.dat" "C:\\Path\\To\\%1.dat"
"C:\\Path\\To\\Gw2.exe" -image

updateAll.bat:
update.bat 1
update.bat 2
update.bat 3

**Comment by Healix** [comment]
If you still want it, I've included it in the last build as a command line option. See the [wiki page](https://github.com/Healix/Gw2Launcher/wiki/Command-line) for more information.

**Comment by SaiyanOfDarkness** [comment]
Assuming this starts at the top of the list and updates them 1 by 1 and replaces the old copy?

**Comment by Healix** [comment]
I'm assuming you meant "C:\\loginfiles\\*.dat"? If the files are actually in the root of C: and that's your system drive, Gw2Launcher would need administrator privileges to modify the files.

If you launch Gw2Launcher with:

Gw2Launcher.exe -update "C:\\loginfiles\\*.dat"

It will look in the folder C:\\loginfiles\\ for all files matching *.dat, such as 1.dat, and launch the updater using those dat files. If the UI doesn't appear, it either didn't find any files, or it failed to update them.

There was a bug in the last release where using the -update option when Gw2Launcher wasn't already running could cause it to hang. I've re-released it with a fix.

**Comment by SaiyanOfDarkness** [comment]
Yeah that update did it.  This works beautifully :)
