### ISSUE TITLE
ArcDPS not working on localized execution

### ISSUE THREAD

**Issue by wistfulglen** [Healix/Gw2Launcher#145]
My account setup currently looks as follows:

1. Gameplay/Main
2. Screenarchery
3. Alt 1
4. Alt 2
5. Alt 3
6. Alt 4

I'm doing localized executions already and have directed ArcDPS to 1, but it doesn't actually show up in game. Would I need to install it to the default GW2 directory as well, or am I doing something else wrong? It doesn't show up under Documents > Guild Wars 2 > addons, and I feel like that might be why it's not working? From what I recall, it used to show up there before I began using Gw2Launcher.

Any help would be greatly appreciated!

**Comment by Healix** [comment]
If you want arc on account 1 (the actual ID can be found under Edit > Statistics), you place arc as d3d11.dll into the Gw2Launcher/1/ folder, or if you're still using DX9, d3d9.dll into the Gw2Launcher/1/bin64/ folder. Localized execution should be set to full. The Gw2Launcher/#/ folder can be found in the main GW2 folder, but won't be created until you launch the account once.

The "addons" folder should appear under the Gw2Launcher/1/ folder.

Arc will fail to load if there's something wrong with its settings. If you had an existing addons folder in the main GW2 folder, Gw2Launcher will have used it as a source. Delete it from the Gw2Launcher/1/ folder to have arc create a new one.

If you're using the addon manager, you'll have to "install" the addons by treating Gw2Launcher/1/ as your main GW2 folder. The addon manager uses its own paths.

**Comment by wistfulglen** [comment]
> If you want arc on account 1 (the actual ID can be found under Edit > Statistics), you place arc as d3d11.dll into the Gw2Launcher/1/ folder, or if you're still using DX9, d3d9.dll into the Gw2Launcher/1/bin64/ folder. Localized execution should be set to full. The Gw2Launcher/#/ folder can be found in the main GW2 folder, but won't be created until you launch the account once.
> 
> The "addons" folder should appear under the Gw2Launcher/1/ folder.
> 
> Arc will fail to load if there's something wrong with its settings. If you had an existing addons folder in the main GW2 folder, Gw2Launcher will have used it as a source. Delete it from the Gw2Launcher/1/ folder to have arc create a new one.
> 
> If you're using the addon manager, you'll have to "install" the addons by treating Gw2Launcher/1/ as your main GW2 folder. The addon manager uses its own paths.

I think I've done all of this already, but it still won't show.

My Gw2Launcher settings:
![image](https://user-images.githubusercontent.com/96360067/166297232-9c333ae7-9ce5-4c53-a79d-fd436fea439c.png)

My Gw2Launcher/1 folder:
![image](https://user-images.githubusercontent.com/96360067/166297395-93579b8a-9cbd-4dfb-b059-8159f55ddd92.png)

My Documents > Guild Wars 2 > addons folder (not sure if it's relevant):
![image](https://user-images.githubusercontent.com/96360067/166297504-3005b4b4-8cff-4c00-9b76-39d1f12e738a.png)

I just checked the arcdps folder under addons, and I think that might be where something is going wrong? I installed it through the addon manager by pointing the installation to C:\Games\Guild Wars 2\Gw2Launcher\1.
![image](https://user-images.githubusercontent.com/96360067/166298287-47250836-6aac-4f65-ac6f-66035c7eedbe.png)

**Comment by Healix** [comment]
Was that the only DLL in the arcdps folder? Because gw2addon_arcdps.dll is the the DLL for arcdps, so it's not going to load without it.

I tried experimenting with the addon manager and what I quickly found out was that it doesn't dynamically check your addons, so if you delete one the DLLs for example, it won't put it back for you. Likewise, if you change the install path, it won't install any addons that were previously installed. After changing the install path, you have to reset it to a clean install, then select which addons you want to update.

**Comment by Healix** [comment]
When you change the path in the addon manager, click the options button under the list of addons and select reset to clean install.

**Comment by wistfulglen** [comment]
> When you change the path in the addon manager, click the options button under the list of addons and select reset to clean install.

Worked like a charm, thanks for the assistance :)
