### ISSUE TITLE
Program crashing randomly

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [Healix/Gw2Launcher#15]
So just going through the settings options and clicking on stuff, the program closes automatically.. no error or anything.  Happening quite often.  I'm on Windows 7 too.

**Comment by Healix** [comment]
Where exactly is this happening? What are the steps to repeat it? Check the log for any details: %appdata%/Gw2Launcher/Gw2Launcher.log

**Comment by SaiyanOfDarkness** [comment]
What I did to replicate at least for sure on one of the occasions.  I right clicked an account and hit Edit.  I went to Launch Options, and then I highlighted text that was typed into the Arguments line (long enough to not fit it all in the same box visually).  And it just randomly closed.

This is what the log told me.  (sorry not sure how to read it).  https://pastebin.com/Fus2WsFE

**Comment by Healix** [comment]
Judging by the log, I'm assuming it's crashing when you move the cursor to the border of the window, as if you were going to resize it. Try this version for a fix:

https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe

**Comment by SaiyanOfDarkness** [comment]
Yeah that seemed to have fixed it.  A few versions previously, this didn't happen, but the last 3-4 releases it started to.  Not sure why though, assuming nothing much changed since?

**Comment by Healix** [comment]
A few versions ago I allowed the account and settings windows to be resized vertically, which was the only notable code where the log said it was crashing. Normally it wouldn't have been a problem, but it was situation where something else could supply a non-standard value and cause it to crash.
