### ISSUE TITLE
DX11 Launching Issue

### ISSUE THREAD

**Issue by TeplarGw2** [Healix/Gw2Launcher#150]
Enabling Dx11 in the launcher causes it to fail and says: "Object reference not set to an instance of an object."
Enabling Dx11 in game as a setting as a work around causes GW2 to freeze for approximately 10 seconds on launch.

I've tried deleting all related GW2Launcher files (in appdata and Guild Wars 2 folders) in attempt to have a fresh reinstall and the problem persists.

Build: 6511
Release: 16
Date: September 24, 2021
The freezing happens on an older build of gw2launcher (pre-Dx11 inclusion).

**Comment by Healix** [comment]
That error is caused by having -dx11 or -dx9 under the account's settings while nothing is set under the global settings. Add anything to the launch arguments under settings. Alternatively, use the [beta version](https://github.com/Healix/Gw2Launcher/tree/master/Gw2Launcher/bin64/Beta).

**Comment by TeplarGw2** [comment]
The first issue is resolved after putting dx11 in the global launch options or using the beta version. 
The second issue still manifests itself but after some further testing, the issue is unrelated to gw2launcher and is happening with dx11 in general. (I thought I had tested this already by launching the game normally but I assumed dx11 was on)

Thank you!

**Comment by TeplarGw2** [comment]
Second issue was resolved with a graphics driver update in case anyone else has the same issue.
