### ISSUE TITLE
Local.dat first use

### ISSUE THREAD

**Issue by samulisoderlund** [Healix/Gw2Launcher#152]
I get this warning _every_ time I launch an account, preventing me from multiboxing. Why is that and how can I fix it?

![image](https://user-images.githubusercontent.com/395737/169647657-e9d94f74-0dd9-4b61-907d-68bb80da6a88.png)

**Comment by Healix** [comment]
It'll show that if it's either the first time that Local.dat file is being used with Gw2Launcher, or the Local.dat file assigned to the account doesn't exist. If you click yes, it'll launch the game as it normally would (1 account at a time) and it should stop showing the message if GW2 successfully starts. If you click no, it should stop showing the message without having to start. If you click cancel, it aborts launching and will show it again on the next launch.

If you click no, let the game launch (no need to go past the launcher), then exit GW2 and launch the account again, does it show it?

Verify the Local.dat file being used under the account's settings (right click > Edit > Local.dat). It'll either be the default Local.dat file or a #.dat file under Gw2Launcher. For the message to show on every launch, either something is deleting this file or blocking Gw2Launcher from seeing it. Try assigning a new file (... > Create new Local.dat file) to see what happens.

**Comment by samulisoderlund** [comment]
If I click No the warning just pops up again. I have to either cancel or start in normal mode. However, I created a new .dat file and I think it's working now. Thanks!
