### ISSUE TITLE
Remembering Graphics Settings

### ISSUE THREAD

**Issue by KTkabo0m** [Healix/Gw2Launcher#154]
Before this I used to manually put in my login for each account as I played. Last account I played on I had the settings down so my computer does not lag or over heat. When I installed GW2Launcher the first time it said something about settings. I thought fine because I already have it set as I want but once I logged in it was mostly to high. When I launched my game without Gw2Launcher and set my settings.. next time I used GW2Launcher it still has all the settings to High and when I use GW2Launcher I cannot change the settings. 

The problem is I WANT to use Gw2Launcher for all my accounts for GW2 but .. I do not want to be forced to play on High. 

How can I change my graphic settings and still use Gw2Launcher?

**Comment by Healix** [comment]
GW2 is in read-only mode and will prevent changes to its settings while allowing multiple accounts to launch. To change any settings, right click the account > Selected > Launch (normal), which will limit you to 1 account at a time.

For graphics settings specifically, most settings can be changed by right clicking the account > Edit > Local.dat > Graphics.

**Comment by KTkabo0m** [comment]
Okay well before I could test that it remembered the setting this time .. a new issues came up which I made a new thread about since it is a different issue: [https://github.com/Healix/Gw2Launcher/issues/154](https://github.com/Healix/Gw2Launcher/issues/154)

**Comment by KTkabo0m** [comment]
Okay the Graphics setting saved this time. Thank you
