### ISSUE TITLE
First acct on list Login never remembers

### ISSUE THREAD

**Issue by KTkabo0m** [Healix/Gw2Launcher#157]
I am having issues figuring this one out. All other accounts are remembered except the first on my list. It is fine until I lose the launcher and then next time I launch it it cannot remember the login anymore. It leaves it blank but when I check it is there in the settings. Then I put in the login and then launched and played a bit and closed it but kept the launcher open as when I close it that happens again (only with the first account on the list). So this time it remembered the email login but not the password. I even clicked remember on the GW2 itself where it types in the login .. still won't put in the password and is unchecked in GW2 itself again. Clicking remember the login in the Gw2Launcher seems to do nothing with the first account. I can't figure this out but it is annoying. The whole reason I wanted the Gw2Lancher is to make it easier on my Carpal Tunnel not to have to type in all the logins every time I play. (Heck even in game I rebound the "use" key to a mouse side button due to my Carpal Tunnel). This has been happening over the last few days but I kept thinking maybe next time it will work... Nope.

**Comment by Healix** [comment]
Do you mean your password is lost when you close Gw2Launcher or GW2? 

If you mean Gw2Launcher - you're using the option to have Gw2Launcher automatically enter your login - that password must be being corrupted when either saving or loading, which may prevent other settings from being saved or just that password. It sounds like it's only corrupting the password, as the email wouldn't be being saved either (or any settings changed after setting the password). Just to be clear, if your password isn't being saved, the password will be blank, whereas if it is being saved, it'll say "change password" and if you click it it'll be blank and give the option to revert it. Right click any account > Settings > Security. Change the encryption to portable or unencrypted. Check if your password is being saved. If it's still not, set the account's password to - test - and see if that saves. If it does, your password must have a character in it that isn't compatible with Unicode.

If you mean GW2 - you're selecting to remember your email/password on GW2's launcher - note GW2 is in read-only mode when launching, so GW2 won't save any changes to its local settings. To change settings / remember your password, you need to right click the account > Selected > Launch (normal), which will limit you to 1 account at a time.

**Comment by KTkabo0m** [comment]
OKay I added it in settings manually all over again and it seems to be working now. And ya I don't launch more than one at a time as my computer would not be able to handle it lol. But it is good to know that I could. :)

**Comment by KTkabo0m** [comment]
OKay closed it and reopened the Gw2Launcher and it did remember it this time. Seems to be working now! Thanks  👍
