### ISSUE TITLE
problems recognizing my updated client

### ISSUE THREAD

**Issue by luveless** [Healix/Gw2Launcher#159]
since the release of the new build, my gw2 launcher doesn't detect the updated client and tells me "download failed please check your internet connection" for some reason.

**Comment by Healix** [comment]
It'll give that message if Local.dat hasn't been updated to the current build. This will generally only occur if GW2 is patched outside of Gw2Launcher, an old Local.dat file is imported, or in rare cases, Local.dat is out of sync / has been overwritten.

Right click any account > All > Update. If that doesn't fix it, right click the account > Selected > Launch (normal).

**Comment by luveless** [comment]
it works thx so much for help!.
