### ISSUE TITLE
Daily login icon not showing

### ISSUE THREAD

**Issue by GW2maniac** [Healix/Gw2Launcher#162]
The little chest icon that indicates accounts with available login rewards is no longer appearing for me.
I have used GW2Launcher for a while with no issues until I reinstalled windows. I used the backup method to import my accounts and everything works as it did before except the icon.
Thank you for your hard work

**Comment by GW2maniac** [comment]
Just showing some accounts with last login 3 days ago with no icon


![Screenshot 2022-06-17 180646](https://user-images.githubusercontent.com/107685265/174345387-7b916e32-9e97-4275-aa57-2b693668efaf.png)

**Comment by Healix** [comment]
Have you not used these account for 3 days, or is the last login not updating? Because the login not updating is a problem with the pre-DX11 build of Gw2Launcher when using DX11, however this wouldn't prevent the icon from showing.

Are you sure you have the icon enabled? Right click the account > Edit. "Show daily indicator" should be checked.

**Comment by GW2maniac** [comment]
The show daily indicator was not enabled on all the accounts, thank you for your help

**Comment by 1Nor1** [comment]
To me is different when i launch my accounts it appears on all of em at first but when i close em it remains on some but not on others and all of em have the check for show daily indicator (using latest stable version btw)
![OTCiGHz](https://user-images.githubusercontent.com/63426232/174448648-19a8470f-c28e-4ef1-a806-e29a10c8956c.png)

**Comment by Healix** [comment]
The purple star is the daily achievement indicator. Unlike the login indicator, it has to be manually toggled or linked to the API (if the account isn't at the 15k cap). If you don't want it, select all the accounts with the icon, right click > edit (multiple) > uncheck "show daily achievement indicator" and ok.

**Comment by 1Nor1** [comment]
oh i want it to show, i have the api of all my accounts and added them to each of em and non are above 15k ap , but i guess it may be more of an api delay situation since so many accounts lol?

**Comment by Healix** [comment]
The API can take up to 10 minutes to update and the account has to played (on a character) for at least 1 minute. Gw2Launcher checks the API when the account exits, and if the API hasn't updated yet, it checks again after 5.5 and 11 minutes, at which point it assumes the daily wasn't completed. If Gw2Launcher can't access the API, it'll retry every minute for 5 minutes, then abort.
