### ISSUE TITLE
Time since last login (not sure if it's a bug or not?)

### ISSUE THREAD

**Issue by TechnoDudeUK** [Healix/Gw2Launcher#168]
I have the launcher setup with 30 accounts, all cloned off the first.
When I login on the first account I get a 'time since last login' displayed beneath the account name.
On all 29 Alt accounts it always show last login as 'never'.
If I edit one of the Alt accounts and look at the Statistics tab it will tell me how many times the account has been launched.  They have all been launched more than once.

Useful to know last launch time in case any crash on load... that way I can spot which ones failed but, with them all saying 'never' it is impossible to tell.

Thx in advance

**Comment by Healix** [comment]
Update Gw2Launcher. That problem occurs with the pre-DX11 version of Gw2Launcher when GW2 is using DX11.

**Comment by TechnoDudeUK** [comment]
Awesome.  Updated and problem all resolved.  Thanks for your help.

I'm new to GW2Launcher having used LaunchBuddy for the last few years.  I'm already preferring Launcher and it's made launching all 30 accounts sooo much easier to configure.  Thanks for a great project.
