### ISSUE TITLE
Launch additional apps

### ISSUE THREAD

**Issue by Sikksens** [Healix/Gw2Launcher#17]
Hey there,

Just started using your app for my extra account I just bought and was wondering if it's possible to launch other apps (Taco/BlishHuD) when launching GW2?

**Comment by Healix** [comment]
Under launch options (for a specific account: right click an account > edit | for all accounts: right click > settings), there's an option at the bottom to run commands after launching. For taco, you'd use the following:

> cd c:\example\path\to\folder\containing\taco\
> start GW2TacO.exe

(taco uses the location of where it was started from, hence the initial change directory)

You should be able to do the same for BlishHUD or any other GW2 overlays, assuming they don't need to be managed (as in they close on their own when GW2 closes).

**Comment by Sikksens** [comment]
That's great, thanks so much!!
