### ISSUE TITLE
Failed when launching game

### ISSUE THREAD

**Issue by Jkwan01** [Healix/Gw2Launcher#174]
When launching my accounts the launcher just says failed even after I update. Launching directly from the official launcher works fine and the launcher used to work just fine. Not sure what the issue is.

**Comment by Healix** [comment]
If you're not using the [beta version](https://github.com/Healix/Gw2Launcher/tree/master/Gw2Launcher/bin64/Beta), right click any account > Settings > Guild Wars 2 > Launch options. Add anything to the launch arguments. There's a bug in the release version where using -dx9 or -dx11 on an account while the global arguments are  blank will cause it to fail with the reason "object reference not set" - you can hover over the failed account to see the reason.
