### ISSUE TITLE
Launcher Automatic Sign-in Delay Issues

### ISSUE THREAD

**Issue by Atros04** [Healix/Gw2Launcher#182]
Recently I have been finding that the delay the program executes to login to the game is no longer long enough. I often find the launcher puts in my password for the user information or outright does not input anything which launches my default profile. The only thing I can note that has changed with my PC recently is I have taken up some coding bootcamp which has me installing an array of programs, however that should not affect the speed at which this program loads.

I can provide gifs of loading to supplement the issues.

**Comment by Healix** [comment]
Use the [beta version](https://github.com/Healix/Gw2Launcher/tree/master/Gw2Launcher/bin64/Beta). The patch on July 19 made GW2 take longer to load and caused a lot of other problems (for example, GW2 no longer reliably remembers the login for some people).

**Comment by Atros04** [comment]
The beta version has been working through the last couple of patches. The only issue I am seeing is the automatic play option is not functioning. The checkbox is checked with no change in behavior.

**Comment by Healix** [comment]
Which automatic play option? The "auto-play" checkbox on the launcher or the one under Gw2Launcher's settings? Are you using Gw2Launcher to enter the login or is it remembered by GW2?

**Comment by Atros04** [comment]
GW2 Launcher settings under an auto-login setting.
![Capture](https://user-images.githubusercontent.com/74441453/187046710-78187258-c0c9-4ba7-8d3d-b1a0e46dc8ba.PNG)

**Comment by Healix** [comment]
I'm assuming the automatic login is working? Launch an account or start Gw2-64.exe directly (you only need to see the launcher). Click the >> next to "Automatically login to character select" in the screenshot. If the play button has been manually changed, try disabling that first, otherwise enable overriding the play button, then click and drag the + to the center of the play/ready button on the launcher.

**Comment by Atros04** [comment]
Okay, that worked. Seems like those settings carried over from my uninstall and reinstall of the beta.
