### ISSUE TITLE
Taskbar icons not grouping

### ISSUE THREAD

**Issue by igorchook** [Healix/Gw2Launcher#184]
Hello,
Thanks for this awesome bit of software!
I recently changed all my accounts to share the same .dat file, excluding one. Since then, the taskbar icons won't group. I fiddled around with it for ages to no avail. I tried to start over by deleting all the account files including everything from the data folder, but the issue persists. Also (not sure if this is directly related), at the same time, my Logitech Gaming Software stopped recognizing the game when launching from Gw2Launcher. So I had to change its link to the GW2.exe that's in the Guild Wars 2/Gw2Launcher/acc# folder, which I never had to do before (I don't think). I'm using localized execution, excluding add-ons, desired level: full, synchronizing: core (I wanted to manually add add-ons to only the main account). I'm on the Beta version (build 6706, release 16, 02/18/2022).

Any advice would be greatly appreciated :)

**Comment by Healix** [comment]
Localized execution set to full gives each account its own path to GW2. Any software that works based on the absolute path to Gw2-64.exe must be configured per account, since the path changes to Gw2Launcher/#/Gw2-64.exe. Grouping isn't possible in this case, since grouping works by combining programs of the same path.

Localized execution set to binaries gives each account its own bin64 folder. This wouldn't require changing any paths and would allow for grouping, but it only works for DX9, whereas DX11 addons go in the main folder and would apply to all accounts.

**Comment by igorchook** [comment]
Oh, I see. It's the setting to full that did it then. So, is there a way to put addons on only one account? Just change it back to  binaries only, or turn off localized execution altogether (are there any downsides to this)?

**Comment by Flomix** [comment]
What I did to achieve this is just configuring arc for dx9, and using the -dx9 flag on the main and -dx11 on all other accounts. Will stop working eventually but as long as anet doesnt drop dx9 support it does the trick

**Comment by igorchook** [comment]
Would that work if I'm using the Unofficial Add-on Manager? I'm not sure if I wanna go back to dx9 for actual gameplay though, my performance improved quite a bit with the switch to dx11.
Thanks for the info!

**Comment by Healix** [comment]
If you specifically want grouping, I've added an option to force it in the [beta version](https://github.com/Healix/Gw2Launcher/tree/master/Gw2Launcher/bin64/Beta). 

I can't add new settings to the beta version, so I've been using a temporary file. Launch it once to generate the settings, then exit (these settings are only loaded on launch). Press WindowsKey+R to open the run dialog, then open:

notepad %appdata%\Gw2Launcher\data\temp\settings.txt

Change the following line:

ForceTaskbarGrouping=1

~

As for DX11, localized execution set to full is required if you want to customize addons per account. There is a way I could disable addons per account without using localized execution, but it would require running Gw2Launcher as an administrator, may have side effects and would slow down launches (toggling addons must wait for the game to reach character select).
