### ISSUE TITLE
Daily indicator not showing up in other accounts

### ISSUE THREAD

**Issue by CottenCode** [Healix/Gw2Launcher#186]
My primary account has a daily indicator but it doesn't show up for my other accounts. For reference, I've enabled both options under Daily Achievements for all accounts. 
![image](https://user-images.githubusercontent.com/13410861/185805396-9f067524-b68e-4cf2-a847-802f52942f3e.png)
![image](https://user-images.githubusercontent.com/13410861/185805416-fdb818bc-7b5f-4491-8331-7e8ce42d4a5c.png)

**Comment by Healix** [comment]
Daily achievements under the tools section is for the popup list of daily achievements. For the account indicator, right click the account > Edit. Look for the daily reset section near the bottom (under the default General tab).

**Comment by CottenCode** [comment]
Hi, thank you for the quick response! I apologize. I'm unsure how I managed to turn the daily indicator on for the first account if I couldn't figure it out for my other alts. Again, thank you.
