### ISSUE TITLE
[Request] add a top bar with a 'kill all processes' button

### ISSUE THREAD

**Issue by SullieLore** [Healix/Gw2Launcher#19]
Hello,

This is an awesome piece of software. However, lately I've been using the 'kill all active processes' option which requires several clicks and gets a bit laggy when I have several clients open.

A single button to kill all processes would be appreciated and I think the best place could be at the top of the program.

This option should be a advanced selection so it doesn't show by default.

Thanks for your consideration!

Sullie

**Comment by Healix** [comment]
You can find the option under Settings > Style in the latest build.
