### ISSUE TITLE
Editing multiple account settings is inconsistent

### ISSUE THREAD

**Issue by Blast1FM** [Healix/Gw2Launcher#192]
The problem at hand: [apply to all accounts does not work](https://i.imgur.com/QbUHVC9.png) with the windowed mode launching setting
Steps to reproduce: Select multiple accounts with windowed mode launch disabled. Edit(multiple) => apply to all accounts => tick the windowed box => ok. 
The setting only applies to the account the mouse was hovering over before clicking Edit(multiple). Rest of the accounts remain unchanged.
Possible(?) workaround - use "-windowed" CLI argument as "apply to all accounts" seems to work properly there

**Comment by Healix** [comment]
This is a little misleading. The checkbox to enable windowed mode should actually be under the window options. The "apply to all" next to the size/position is only for the size/position. If you "apply to all" the window options, then it'll enable windowed mode on all accounts without changing the size/position of those accounts (unless selected to).

**Comment by Blast1FM** [comment]
Fair enough, thank you.
Forgot to mention this was on the beta version, but it shouldn't matter either way.
