### ISSUE TITLE
Launcher writes password in email section.

### ISSUE THREAD

**Issue by Zyhmos** [Healix/Gw2Launcher#195]
Sometimes GW2 opens too slow.
This results in launcher pasting login before the login screen is even open, leaving it empty once it loads. OR if the timing is just right, even pasting password in the email section kekw.

Please add a setting that lets us delay the login paste by X seconds.

**Comment by Healix** [comment]
I'm assuming you're using the release version? Use the [beta version](https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe).

**Comment by Zyhmos** [comment]
Current workaround is to reduce process priority on the launcher while increasing it for GW2.
