### ISSUE TITLE
Addons not working when launching through Gw2Launcher

### ISSUE THREAD

**Issue by Zyga21** [Healix/Gw2Launcher#197]
Ever since a few days ago I've been having issues with arcdps/etc not loading properly and still using an old version on gw2launcher, and after trying out a lot of different things I decided to retry it all and just deleted everything, when I reinstalled arcdps (d3d11.dll) to my main folder (E:\Guild Wars 2) and ran the game without the launcher everything worked fine, then I copied over the local.dat/graphics settings over to gw2launcher and logged in again, but nothing loaded. I took a look at the issues here and tried out multiple things, I tried toggling localized execution on and off, resyncing the folders/deleting them again, looking in the # folder to make sure d3d11.dll is there, running the beta version of gw2 launcher etc. but none of them have loaded arcdps at all. Currently the settings I'm using are like this 
![image](https://user-images.githubusercontent.com/46537451/187251924-cd58e960-4f4d-44ef-b7b6-125ec91ae969.png)

All I want to do is to have arcdps running on at least my main account and the ability to login to other accounts while on my main. Having arcdps running on the alts is good too though, but right now it's just not running on any of them.

**Comment by Healix** [comment]
With localized execution disabled, if GW2 can load Arc, then Gw2Launcher can load Arc. If it didn't, the accounts likely aren't using DX11. You can verify by launching the account to at least character select, then right click any account > Tools > Guild Wars 2 > Verify usage of DX11. To force DX11, add -dx11 to the arguments (Settings > Guild Wars 2 > Launch options) and ensure -dx9 isn't added under the account (Edit > Launch options).

**Comment by Zyga21** [comment]
Forcing it into dx11 worked, thanks.

It was weird though because I hadn't enabled dx9 before
