### ISSUE TITLE
In game Language not Configurable

### ISSUE THREAD

**Issue by MWShurikan** [Healix/Gw2Launcher#198]
Hi,

I seem to not be able to configure the in game language of my gw2 accounts. 
If I start GW2 regular, it starts in English (like intended).
If I use the Launcher, it somehow defaults to a German version (my windows language is German).
Is there a way to set the language that should be used ? I can't find it in the configuration. If not, this could be seen as 'feature request'.

**Comment by Healix** [comment]
GW2 defaults to your system language, so whenever you create a new Local.dat file, it's going to be German. Your simplest option would be copying an existing Local.dat file that is already set to English whenever you need a new file. Right click the account > Edit > Local.dat > ... > Copy from an existing file (%appdata%\\Guild Wars 2\\Local.dat). If you don't need GW2 to remember your login, you could also share this file with other accounts.

Note that GW2 will prevent changes to its "local" settings while it's allowing multiple clients to start, so if you want to change the language on the launcher, you have to right click the account > Selected > Launch (normal).
