### ISSUE TITLE
[Request] Auto character login

### ISSUE THREAD

**Issue by barbarolucente** [Healix/Gw2Launcher#199]
Sorry if it's not the place where request a feature but i don't know how github works =D

I've seen that if you press "enter" right after "Play" (when the white/black screen comes out) it will auto login the selected character in the characters screen.
The characters screen pop up, receive the "enter" like i'm pressing it in that moment and login the character.

My question: is it possible to put an option for Gw2Launcher to do this? Maybe per account?
Thanks for your work!

**Comment by Healix** [comment]
Automatically logging in to a character would be against the rules.

**Comment by barbarolucente** [comment]
ç__ç

Thanks for the reply!
