### ISSUE TITLE
arcps doesn't work with Gw2Launcher

### ISSUE THREAD

**Issue by f4rv3l** [Healix/Gw2Launcher#2]
As the title sais, arcdps is not working with Gw2Launcher. Are there any plans to change this issue?

-greetings

**Comment by Healix** [comment]
If you're using the automatic login option (-nopatchui), GW2 will ignore any DLLs added to its bin folder. You'll need to disable that option if you want to use arcdps.

arcdps also only supports running in one client at a time.

**Comment by f4rv3l** [comment]
Ahh, now it works! Thank you very much.

**Comment by f4rv3l** [comment]
Hey there!

Has  anything changed the past two years? Is it possible to run arcDPS / ReShade on all clients now? Just want to stay up to date. :)

**Comment by Healix** [comment]
If you want to use mods on various accounts, enable:

Settings > General > Launching > Give each account its own executable path

On your next launch, a Gw2Launcher folder will be created in your GW2 folder, which will contain a numbered folder for each account you launch. Each account will have its own virtual copy of GW2's folder, allowing you to customize the mods for each account.

Note that when updating a mod, each folder is independent so you'll need to update each one. If you simply want to run the same mods on all accounts, only update the default bin folder, then delete the Gw2Launcher folder to have it recreated on the next launch.

**Comment by f4rv3l** [comment]
Thank you very much for explanation.
