### ISSUE TITLE
Improper Window Scaling when Windows DPI Scaling is enabled

### ISSUE THREAD

**Issue by FlamingOven** [Healix/Gw2Launcher#20]
I have a 4K monitor on my left, 1080p in the middle, and 1080p on the right.

I put all my 4 accounts in the middle monitor, with one in each corner, identically sized to take up the full screen.

When I turn on 150% scaling for my 4K monitor, the option in GW2Launcher to "Launch with the -windowed option using the following size" does not function correctly for some windows. The windows with issues are the windows that are on the the middle 1080p monitor, but the left edge of the window is touching the edge of the 4K monitor.

These buggy windows are improperly sized compared to the window preview. While they are loading with a white screen they are sized properly, but when they reach the character select screen, these windows resize to take up the full 1080p monitor and have to be resized manually.

Turning off scaling on the 4K monitor solves the issue but is a workaround.

Thanks for your time.

**Comment by Healix** [comment]
Right click Gw2Launcher (either the exe or a shortcut) and select properties. Select the compatibility tab, then click "change high DPI settings" near the bottom. Check "override high DPI scaling behavior" and select "application" under it. This should prevent Gw2Launcher from being automatically scaled by Windows (via stretching). If you still want it to scale, you may additionally check "use this setting to fix scaling problems..." and select when "I opened this program" under it.

**Comment by FlamingOven** [comment]
That fixes the issue I was having. Thanks.
