### ISSUE TITLE
What is the code licensed under?

### ISSUE THREAD

**Issue by dlamkins** [Healix/Gw2Launcher#21]
I couldn't find in the UI or in this repo any mention of what this application's source code is licensed under.

Has that been specified somewhere that I've just missed, or is the code currently unlicensed?

https://choosealicense.com/no-permission/

**Comment by Healix** [comment]
It was nothing, I guess, though I believe it used MIT back on Google. I've never cared about this and have always chosen whatever was the default if one was required, so really, feel free to do whatever you want. If it matters to you, I've added the default MIT license.

**Comment by dlamkins** [comment]
Thanks for doing that so quickly!  It is very much appreciated.  🙂
