### ISSUE TITLE
export (in beta) bugs

### ISSUE THREAD

**Issue by wharlox** [Healix/Gw2Launcher#210]
passwords are not exported (even when selected)

beta build 6710, release 16, (date 5hrs ago)

Edit: totp codes are exporting fine (initial test was bad on my part)

Hoping the import works with passwords for batch editing

**Comment by Healix** [comment]
Basically every new feature in the beta version is unfinished. In this case exporting passwords was simply disabled. I've enabled it in the latest beta release.

**Comment by wharlox** [comment]
much appreciated!
