### ISSUE TITLE
Trading Post Favorites?

### ISSUE THREAD

**Issue by nicus9** [Healix/Gw2Launcher#212]
How do I use this in conjunction with Trading Post favorites? 
I select them but when I close and relaunch the game, they're gone.

I unfortunately didn't realize this until after I went through and added favorites to all my alts........

**Comment by Healix** [comment]
GW2 won't save any "local" settings when it's allowing multiple clients. To favorite something, you'll need to right click the account > Selected > Launch (normal), which limits you to 1 account at a time.

Note these settings are stored in Local.dat, so if you're sharing that file with other accounts, your favorites will appear on all of them.

**Comment by nicus9** [comment]
Ah ok, thank you very much
