### ISSUE TITLE
All accounts launch without changing credentials

### ISSUE THREAD

**Issue by MikSki17** [Healix/Gw2Launcher#213]
Hi,

After I've reset my PC apart from SSD where I had Gw2 installed and downloaded Gw2Launcher again, any account I add and try to launch, it doesn't change credentials and just hits play which launches my main account. I do have automatically type email and password turned on. Sometimes it even types password in email field. I've never had this issue before so I'm wondering if it's because I didn't download Gw2 from scratch, I just ran repair exe on the files I had from before resetting PC, because that worked and saved me downloading time. How can I fix this? TIA

**Comment by Healix** [comment]
Use the [beta version](https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe)

**Comment by MikSki17** [comment]
That worked, thanks!
