### ISSUE TITLE
Automatic Login doesn't work

### ISSUE THREAD

**Issue by good-live** [Healix/Gw2Launcher#22]
Hey,
after a recent reinstall of my pc it seems that the autologin feature doesn't work anymore.
I store the credentials in the games launcher itself which is working fine (Got one Local.dat for each account) But whenever i start one i have to manually press "Login" for the game to start. That's a bit annoying. Is there any setting that i'm missing?

**Comment by Healix** [comment]
Right click any account > Settings (or Edit if you only want to apply this to 1 account) > Launch options > Automatically login on the launcher

This is the standard -autologin option for reference, which is only used for accounts that have their credentials remembered by GW2 itself.

If you also want it to automatically play (without the 5s delay of the normal auto-play option):

Right click the account > Edit > Launch options > Automatically "play" after logging in

**Comment by good-live** [comment]
Awesome ty
