### ISSUE TITLE
auto character login

### ISSUE THREAD

**Issue by latency-dev** [Healix/Gw2Launcher#222]
I have quite a few alt accounts and wanted to save time on daily logins with automatically selecting the first character to login after window is up (send enter key) and follow up with automatically closing the window after map loads.

Is there a straight forward way to implement, looking for any clues or suggestions on how to add this in the code.

**Comment by Healix** [comment]
A few people have requested automatically loading a character. It's trivial, but it'd allow botting and thus isn't allowed.

To close the game, you can set a program to run after launching under the launch options. Select shell commands, run after loading a character (in beta) and set the commands: taskkill /PID %processid%
