### ISSUE TITLE
Launching multiple Accounts error

### ISSUE THREAD

**Issue by OhKeey** [Healix/Gw2Launcher#235]
Hi there,

so I've the problem, when I'm trying to launch more than 10 Accounts in a row - GW2 replies with an network error code. I am aware of the fact that this could be solved with a VPN but unfortunately I don't have one. 
Is there any solution for that problem? From what I saw in another question was the recommendation to use the beta and enable "localized execution" with full desired level. But that doesnt work for me :(

**Comment by Healix** [comment]
GW2 has a limit per IP on how quickly you can login to multiple accounts and the total number of accounts you can login to (~30). If you spam logins for example, each one will take an increasing amount of time to complete until its times out, and it won't lessen until you stop all login attempts (it takes ~60 second to reset).

The first limiter can be avoided by enabling the automatic limiter under Settings > General > Launching. The second limiter can't be avoided without changing your IP (I only know people generally try again hours later or use a VPN).

If you're using SMS, it has its own limiter that will give a 3005 error (meaning too many SMS requests).

**Comment by OhKeey** [comment]
So the only solution - instead of a vpn - would be just to wait some time before I launch another 15 accounts?

**Comment by Healix** [comment]
Yes. If you have no way to change your IP, you'll have to wait it out.

**Comment by OhKeey** [comment]
Alright, thank you for your help :)
