### ISSUE TITLE
What is the different between Encryption Portable and Unencrypted?

### ISSUE THREAD

**Issue by Rainrainraind** [Healix/Gw2Launcher#237]
What is the different between Encryption Portable and Unencrypted?

If you are allowed to transfer it to other PC wouldn't it be the same as Unencrypted?

**Comment by Healix** [comment]
Unencrypted has your password in plain text. You could open the settings in notepad to see it.

Portable encrypts the password to your settings. Anyone with the file would be able to use your login, but not decrypt it as easily.
