### ISSUE TITLE
Exclude d3d11.dll to other accounts

### ISSUE THREAD

**Issue by Rainrainraind** [Healix/Gw2Launcher#239]
Hi.. I'm using
Mode: Basic
Options: Restore the original path while not in use + Clear temporary files while not in use
Localized Execution: Unchecked
Localized CoherentUI: Unchecked

I'd like to use ArchDPS on only my main account, can it be done?

**Comment by Healix** [comment]
Localized execution set to full is required for that. Configure it to exclude addons and only sync core files. After enabling it and launching the account once (you don't need to login), you'll find a Gw2Launcher folder where Gw2-64.exe is located, and in that folder will be a # folder for the account. Only put d3d11.dll in that account's # folder (# is the ID of the account found under Edit > Statistics).
