### ISSUE TITLE
Rearranging Account Folder # and Graphic XML # 

### ISSUE THREAD

**Issue by Rainrainraind** [Healix/Gw2Launcher#240]
Hi is it possible to assign the number of the account  folder ID? right now it shows my main account folder ID as "5" I would like it to be "0" or "1" follow by the other account folders to "2" "3" "4"

as well as the graphic XML file, it shows "5" and "6" instead of the starting number.

So I was thinking how can I restart the number? from 0-10 etc instead of skipping the initial digit

**Comment by Healix** [comment]
You'd have to start over. The ID is always +1 of the last ID, so you can only reset it by starting Gw2Launcher with no accounts, which starts back at 1.

You can retain some account information by exporting (Settings > Backup > Export) all accounts. If you want the accounts to be in a different order, you'll have to modify the file to change the order they're listed in. Exporting in CSV will probably be easiest.

Delete %appdata%\Gw2Launcher\settings.dat to reset all settings / delete all accounts.
