### ISSUE TITLE
Questions regarding to the new MumbleLink  login indicator

### ISSUE THREAD

**Issue by Rainrainraind** [Healix/Gw2Launcher#241]
Hello, under "Tweaks" I have "Daily login" "Use MumbleLink to track daily login" Checked

However I don't see any indicator, I launched the account and my character into the game.

Currently all my alt accounts are set to "-mumble 0" to prevent blishhud from attaching to these accounts.

**Comment by Healix** [comment]
The daily login indicator is the chest icon (Edit > General > Show login indicator).  When you login, the icon is hidden. With the MumbleLink feature, the icon isn't hidden until you load a character.

0 isn't a valid name (it has to start with a letter), so that effectively disables GW2 from creating a link.

**Comment by Rainrainraind** [comment]
Do I need to have a API key for the mumblelink to work?
I tried using this but it didn't work, I don't see a chest icon.
" MumbleLink_%accountid% "

**Comment by Healix** [comment]
The API is unrelated. MumbleLink is public memory where GW2 writes information about your play session.

The chest icon will only be shown if you haven't logged in today. It looks like the login rewards chest ([see the preview](https://raw.githubusercontent.com/wiki/Healix/Gw2Launcher/images/preview.jpg)). It's enabled by default, so if you've never seen it, you may have disabled it.

**Comment by Rainrainraind** [comment]
It's working now! Thank you so much for the help.

Thank you for adding more features and continuing updating this wonderful tool! 

Appreciated it!
