### ISSUE TITLE
Daily login reward indicator

### ISSUE THREAD

**Issue by DasMu3sli** [Healix/Gw2Launcher#243]
Since the new version , the indicator is shown until a character is fully loaded.

At least for its useless now, because for login multiple accs is not nessesary to load the character completly.
Its enough to just start loading and then you can close the game and still get the login-reward.

Maybe its possible the make it selectable, if you want the inmdicator the be shown until character is loaded and game ist started. 

Ty anyway for the great work :)

**Comment by Healix** [comment]
You can disable the use of MumbleLink to track the login under Settings > Guild Wars 2 > Tweaks. If you want to disable it for a specific account, you could change the mumble link name for that account to 0 (GW2 will disable the use of MumbleLink if the name starts with a 0).

**Comment by Healix** [comment]
Re-download the latest release for an option to disable it per account. It's in the same section as the login indicator and daily login day.

Note you can select multiple accounts > right click > Edit (multiple) to change them all at once.

**Comment by Rainrainraind** [comment]
by "start loading" do you mean by load the character and close the game? or do you mean by loading the game to the character selection page and close the game?

**Comment by DasMu3sli** [comment]
> by "start loading" do you mean by load the character and close the game? or do you mean by loading the game to the character selection page and close the game?

load the character
i wait 2 seconds before i close the game, but I am not sure if you have to wait any time

**Comment by DasMu3sli** [comment]
> Re-download the latest release for an option to disable it per account. It's in the same section as the login indicator and daily login day.
> 
> Note you can select multiple accounts > right click > Edit (multiple) to change them all at once.

it works 
tyvm for the fix
