### ISSUE TITLE
What Build is Installed ?

### ISSUE THREAD

**Issue by SeparGW2** [Healix/Gw2Launcher#25]
Can I view the build number that is installed in my system?

**Comment by Healix** [comment]
Right click Gw2Launcher.exe > properties > details. See the last number in the file version.

**Comment by SeparGW2** [comment]
Thanks - I was looking for a number inside the program somewhere - did not consider the system file properties.

    On Saturday, March 21, 2020, 1:58:05 PM EDT, Healix <notifications@github.com> wrote:  
 
 


Right click Gw2Launcher.exe > properties > details. See the last number in the file version.
