### ISSUE TITLE
hot key for launch daily 

### ISSUE THREAD

**Issue by jor8888** [Healix/Gw2Launcher#256]
anyway for hotkey not to launch the accounts with daily login chest not checked  or remember account name and password not checked?  I dont want the hot key to launch free to play accounts

**Comment by Healix** [comment]
It _is_ only supposed to launch accounts showing the daily login indicator, but it's bugged. I had separated how the daily login was tracked at the last minute and missed a few changes.

Use the [beta version](https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe) for a fix.

Alternatively, put all of the accounts you want to login to on a different page (right click > Selected > Show on page) and show that page (scroll the top left menu button or click it to switch pages). Only accounts on the currently selected page will be launched.

**Comment by jor8888** [comment]
awesome thx
