### ISSUE TITLE
Multiple Addon configs

### ISSUE THREAD

**Issue by Flomix** [Healix/Gw2Launcher#257]
I have the following need:
I need 2 different run configurations, one with a specific addon (an additional dll in the game directory) and a second with another additional dll. I wasn't able to find a way to configure the launcher that way.

One solution that came to my mind was creating a "cloned" GW2 folder using hardlinks, adding the dll to it and using different game directories for different accounts. But the Launcher seems to not support that, i can only configure the game dir globally and can't override it for a specific account.

**Comment by Healix** [comment]
To have 1 account that uses different addons, you'll need 2 accounts, so start by cloning it (right click > clone).

Localized execution (Settings > Guild Wars 2 > Management) will give each account its own GW2 folder (using hard links). Enable it and set it to exclude addons, full, core and to only include the cloned account (if you only want this 1 account to have different addons). Launch the cloned account and you'll find a Gw2Launcher\\# folder where Gw2-64.exe is located. Place any addons you want on this account in the # folder.

**Comment by Healix** [comment]
As of the last release, you can select which accounts use localized execution, allowing for only 2 out of 2002 accounts to use different files. Is that not what you're wanting?

**Comment by Flomix** [comment]
okay now i'm impressed, that was exactly what i was after 😍  Quite a sneaky gem, that you can only see it when you enable that checkbox, yeah it seems to cover exactly what i asked for ^^
