### ISSUE TITLE
Proper reinstall

### ISSUE THREAD

**Issue by wistfulglen** [Healix/Gw2Launcher#258]
I used this about a year ago and have since deleted the .exe, but now that I'm wanting to reinstall it, it still remembers all the info I put in previously. Is there a way to just clean everything up so I can start from a blank slate?

**Comment by Healix** [comment]
Open any folder. In the address bar, enter the following and press enter:

%appdata%

Under that folder will be a Gw2Launcher folder. This is where everything is stored. Delete it.

**Comment by wistfulglen** [comment]
> Open any folder. In the address bar, enter the following and press enter:
> 
> %appdata%
> 
> Under that folder will be a Gw2Launcher folder. This is where everything is stored. Delete it.

Thank you!
