### ISSUE TITLE
Crash on one account only.

### ISSUE THREAD

**Issue by Squidknig** [Healix/Gw2Launcher#263]
I have 34 accounts,  this morning number 34 started giving an error for Username/Password

I logged in and changed it, then updated it in Launcher,  Crashes before character loading screen

Deleted the account on Launcher,  made a new entry for it.
Enter username / password,  accepted, then crashes in the exact same place.
Tried deleting temp files under appdata,  still crashing in the same place.
Tried run normally,  crashes. 

Here is the log:

00000779: Perf: Build 141623
00000779: Perf: 2023-02-23T15:24:33Z
00000779: Perf: Platform 1
00000930: Perf: Archive has version 1 header
00001273: Perf: Archive has version 1 header
00001936: Perf: Deleted 0 old files.
00001976: Debug: WebBrowser: Skipping file C:\Guild Wars 2\bin64\CoherentUI_Host.exe
00001977: Debug: WebBrowser: Skipping file C:\Guild Wars 2\bin64\CoherentUI64.dll
00001977: Debug: WebBrowser: Skipping file C:\Guild Wars 2\bin64\icudtl.dat
00001977: Debug: WebBrowser: Skipping file C:\Guild Wars 2\bin64\libEGL.dll
00001978: Debug: WebBrowser: Skipping file C:\Guild Wars 2\bin64\libGLESv2.dll
00001978: Debug: WebBrowser: Skipping file C:\Guild Wars 2\bin64\D3DCompiler_43.dll
00001978: Debug: WebBrowser: Skipping file C:\Guild Wars 2\bin64\d3dcompiler_46.dll
00001978: Debug: WebBrowser: Skipping file C:\Guild Wars 2\bin64\ffmpegsumo.dll
00001978: Debug: WebBrowser: Skipping file C:\Guild Wars 2\bin64\pdf.dll
00001978: Debug: WebBrowser: Skipping file C:\Guild Wars 2\bin64\blink_resources.pak
00001978: Debug: WebBrowser: Skipping file C:\Guild Wars 2\bin64\content_resources_100_percent.pak
00001978: Debug: WebBrowser: Skipping file C:\Guild Wars 2\bin64\theme_resources_standard.pak
00001978: Debug: WebBrowser: Skipping file C:\Guild Wars 2\bin64\ui_resources_100_percent.pak
00005354: Debug: Coherent Warning: PID: 2856 | 7124 15:24:37.850562 [2856:7124:WARNING:resource_bundle.cc(303)] locale_file_path.empty()
00012016: Debug: Coherent Warning: PID: 2856 | 7124 15:24:44.704649 [2856:7124:WARNING:(0)] locale_file_path.empty()
00017191: Debug: Coherent Warning: PID: 2856 | 17672 15:24:49.902681 [5320:7460:WARNING:resource_bundle.cc(303)] locale_file_path.empty()
00018691: Debug: Web Message (launcher.js:2): onShowLauncher
00018691: Debug: Web Message (launcher.js:2): onSetPreferences
00018691: Debug: Web Message (launcher.js:2): onSetLanguage
00018716: Debug: Web Message (launcher.js:2): onPasswordHash
00053792: Debug: Connecting to auth server 34.237.20.65:6112...
00053841: Debug: Gc::GcAuthCmdNotify

**Comment by Squidknig** [comment]
I did some more trouble shooting, 

I copied a dat from one of my working accounts,   renamed it to point to this account.
I can run just fine using Lauch Normally on the account,  just not when using launch

**Comment by Healix** [comment]
Crashes how? Does it show the error report window? The log you posted is Gw2.log, which is for the launcher/patching. The crash log is ArenaNet.log. Click show details on the error report window to see the crash log.

Are you using DX11 on all accounts? DX11 is now being forced; they've been rolling it out in waves (DX9 will be removed in April). I wouldn't have expected the rollout to be based on the login, but if it was, it would require logging in once to activate it, which would explain why you can only get it working once. If you were to create a new Local.dat for the account, it would default to DX11, so I'm guessing that would fail, whereas using an old Local.dat that's still configured to use DX9 would work once before it's changed to DX11 on exit.

**Comment by Squidknig** [comment]
![image](https://user-images.githubusercontent.com/126182056/220970990-63a2d538-cc2b-453e-bfae-a5c2f81bc9e6.png)
[Crashlog.txt](https://github.com/Healix/Gw2Launcher/files/10816004/Crashlog.txt)

i am not using DX11 on any accounts.

**Comment by Healix** [comment]
Are you sure you're not using DX11 on all accounts? It doesn't actually matter what the checkbox in-game is set to if you're overriding it with -dx9 or -dx11.

Because your crash log says you're using DX11 and also using DX11 addons: 
C:\Guild Wars 2\d3d11.dll
C:\Guild Wars 2\dxgi.dll

**Comment by Squidknig** [comment]
i was editing before i saw your reply.

i went into the Launcher and used the option to force Dx9, it will launch fine now.
How would i fix this when they drop DX9 ?

**Comment by Healix** [comment]
Delete:

C:\Guild Wars 2\d3d11.dll
C:\Guild Wars 2\dxgi.dll

They're likely outdated and causing the crash.

**Comment by Squidknig** [comment]
okay,  i deleted those two files
Went into the launcher and unticked the box for Force DX9.
Still crashing.
went into the launcher and turned the DX9 flag back on,  works fine.
Should I wipe everything and start over?

**Comment by Healix** [comment]
Wipe everything? No.

It may have still been loading the other DX9 addon:

C:\Guild Wars 2\bin64\d3d9.dll

Other potential problems are other software you have that is hooking into the game:

RivaTuner Statistics Server
DisplayFusion
YoloMouse

Some people have reported a problem with shadows after the patch. You could try launching with low graphics settings, which you can change outside of GW2 using Edit > Local.dat > Graphics. Using a new Local.dat would have a similar effect, if you had already tried that.

Beyond that, a c0000005 crash could be caused by anything in the DLL list in the crash log. Basically, GW2 requested memory and something returned an error instead, or it was blocked by security software. You can only guess what's causing it, and it could even be a bug with GW2 itself, and the forums _are_ reporting crashes after the patch, so I'd wait and see. If you want to try anyways, clean install your graphics drivers, run through Windows update, using msconfig to disable all non-Microsoft startup programs/services, and run a system check (command prompt: sfc /scanow).

**Comment by Squidknig** [comment]
Thank you for all the help.
I sent you funds for Coffee.

:)
