### ISSUE TITLE
feature request: option to remove the big-red-x

### ISSUE THREAD

**Issue by wharlox** [Healix/Gw2Launcher#269]
I'd live to have options to remove the big red-x, or have it provide a nag-confirmation, or both. 

It is a bit too easy to accidentally click on, and very sad when I do 

Thanks!

**Comment by Healix** [comment]
What big red x?

**Comment by wharlox** [comment]
after launching an instance, it becomes visible. I guess it is more of a big-red-square with an x in it to kill all instances.

**Comment by wharlox** [comment]
Wait, I found it; the option exists! closing
