### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by JeppexX** [Healix/Gw2Launcher#27]
Hello, i tried changing my interface and save it permanently but it doesn't work in the "game settings" 
 I tried to find an option in the settings/folders but couldn't find a solution. As far as im aware, there's no coding for the interface setting.

JeppeX

**Comment by Healix** [comment]
Except for hardware-related settings (graphics and sounds), GW2 stores all of its settings on the servers. These settings aren't saved outside of the game, and Gw2Launcher has no interaction with them.

If you're wanting to copy settings between multiple accounts, you'll need to do it manually - take a screenshot and compare.

If you're saying GW2 isn't saving these settings, that's a problem with the account. The -prefreset option can be used to return your account's settings to a default state.

**Comment by JeppexX** [comment]
Found a fix, needed to start a launcher "normally" and change it there. Ty for quick response :)
