### ISSUE TITLE
The launcher deletes the original GW2 folder in AppData/Roaming on launch

### ISSUE THREAD

**Issue by VathanaJr** [Healix/Gw2Launcher#271]
Forgive my little understanding about how GW2Launcher works, but is it intended that the folder is deleted every time I launch any of my accounts?

I use the Basic profile management mode, and my accounts have separate .dat files.

This isn't an issue at all if I use only Gw2Launcher, but sometimes I want to use the original launcher, and I have to patch, manually enter credentials, and change the settings. I want my main account .dat and .xml to be in the original GW2 folder for when I use the original launcher. I can do what I just mentioned or copy the files used my GW2Launcher into the folder, but it's extra work either way.

Here are my settings:
![image](https://user-images.githubusercontent.com/84817347/226145012-ae40f67c-4343-4a72-9c82-faa0ef589b31.png)
![image](https://user-images.githubusercontent.com/84817347/226145025-8d9e755d-1c02-43f7-a57c-9ff5f2a5121b.png)

**Comment by Healix** [comment]
Basic mode works by swapping the folder for each account. The original is simply renamed. To have the original restored, enable the first option under basic mode: restore the original path when not in use. You'll then be able to launch GW2 outside of Gw2Launcher, as long as no Gw2Launcher accounts are active.

**Comment by VathanaJr** [comment]
Ok I get it now. Thank you so much!
