### ISSUE TITLE
The Auto-Play" box doesn't stay ticked.

### ISSUE THREAD

**Issue by WoofusX** [Healix/Gw2Launcher#276]
Hey, thank you very much for this awesome piece of software, it really helped me a lot. Recently I changed my PC and I used the backup and restore function which worked flawlessly. However, now the Auto-play box resets every time. On my old PC, I let it launch 8 accounts at a time and they were waiting for me in the character select screen, but now it launches 1 account and doesn't click play, and the other accounts don't launch until the first one is in the character select screen. I launched the game normally, ticked all the boxes, and then exited it with the "Exit to Desktop" option instead of clicking the X to close the game. I am pretty sure this is a user error, I just can't remember what I did the first time. Any idea what am I doing wrong? Thanks in advance!

**Comment by Healix** [comment]
GW2 is in read-only mode while it's allowing multiple clients to launch. If you want to change any of the "local" settings (launcher settings, some graphics, sound and trading post favorites), you have to right click the account > Selected > Launch (normal). Also, GW2 has to properly exit for it to save, so for example if you use Gw2Launcher to immediately terminate GW2, or GW2 crashes, it won't save.

If you just want to auto play, there's alternatively an option under the account's launch options for that.

**Comment by WoofusX** [comment]
"you have to right click the account > Selected > Launch (normal)". This worked! Thank you very much! I hope you will keep this project alive for many years to come, and I hope more and more ppl will donate to support this project.
