### ISSUE TITLE
My accounts have the correct login details stored under settings, but when i launch them they are launching with another account's details?

### ISSUE THREAD

**Issue by Drogon1234** [Healix/Gw2Launcher#285]
I have 17 seperate accounts in the launcher and all 17 have their own correct login details saved. I can see this when i go to account > edit > launch options

For some reason though, if i start account 1 for example, instead of using the login details saved under account > edit > launch options, it is launching with the login details of account 17.

This is basically happening for accounts 1 until 16. Only 17 is using the correct login details, for all the other accounts it is launching with the details of account 17.

Does someone know how i can fix this (preferably without creating 16 new accounts).

**Comment by pitittatou** [comment]
see #284 it is probably the same issue

**Comment by Healix** [comment]
This is likely because the automatic entry broke with the patch, so GW2 is showing its own remembered login, which is stored in Local.dat.

Try the [beta version](https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe) (build 7084).

**Comment by ReportAnIssue** [comment]
It's probably the coherentUI being replaced with Chromium Imbedded Framework,  that is causing the login issues.

**Comment by allenthetall** [comment]
The Beta Version fixed the issue for me, Thanks

**Comment by Drogon1234** [comment]
> This is likely because the automatic entry broke with the patch, so GW2 is showing its own remembered login, which is stored in Local.dat.
> 
> Try the [beta version](https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe) (build 7084).

Thanks! The beta does indeed seem to fix it.
