### ISSUE TITLE
Issue with Updating Accounts

### ISSUE THREAD

**Issue by luigiormario7** [Healix/Gw2Launcher#286]
Hi, 
When I go to launch an account it is constantly crashing/returning an error whilst updating (presumably the .dat file as the game is up to date and can be launched locally).

Assertion: Failed to load file. 

File: D:\Perforce\Live\NAEU\v2\Code\Aerna\Services\LoadHandle\LoadHandle.cpp(160)

Note this isn't due to the recent patch, I simply haven't used the program in while! Any ideas would be appreciated.

**Comment by wharlox** [comment]
are you using the latest beta build? there is a log window that can be opened by right-clicking any account and selecting Tools -> Log; then trying to launch an account

**Comment by Healix** [comment]
Somewhere, your files are outdated. You're using localized execution, so ensure you've not forgotten about old mods. Disable it (Settings > Guild Wars 2 > Management) or delete the Gw2Launcher folder where Gw2-64.exe is located to reset it. 

Worst case, Local.dat has been corrupted, which will require you to delete it. Right click the account > Edit > Local.dat > ... > Create a new file. Right click this account > Selected > Launch (normal). If it now works, you've confirmed it was.

**Comment by luigiormario7** [comment]
Ah thankyou, required recreating the local.dat.
