### ISSUE TITLE
Feature Request: option to disable Left click action for inactive accounts.

### ISSUE THREAD

**Issue by nopponv** [Healix/Gw2Launcher#292]
What I mean is the setting in `Settings > Style > Actions` There is a 'None' action for Left Click for active accounts, but there aren't any for inactive accounts. I would like to have an option for Left Click to do nothing, because when I multibox, I tend to misclick and launch other accounts by accident.

Current situation:
- Run 3 active accounts.
- Left click other active account to switch screen to do things.
- Accidentally left clicking inactive account and it launches as a 4th account.

What I'm wishing for:
- Having the option for Left Click to be 'None' for inactive accounts.
- Then I can still use Middle Click to launch inactive accounts.

English is not my native. If my explanation is not good, please ask me more. Thank you very much.

P.S. I have just switched from LB as it constantly has annoying issues, and found out that Gw2Launcher might be better for me!

**Comment by Healix** [comment]
You can find "none" for inactive accounts in the [current release](https://github.com/Healix/Gw2Launcher/blob/master/Gw2Launcher/bin64/Release/Gw2Launcher.exe?raw=true).

**Comment by nopponv** [comment]
Wonderful! I have been using Gw2Launcher for over a week and I'm loving it. I'm confident to say that this is better than other multibox launchers. Thank you so much for your hard work!
