### ISSUE TITLE
feature request: close to system-tray

### ISSUE THREAD

**Issue by wharlox** [Healix/Gw2Launcher#293]
an option to close window but keep the app open via system-tray would be wonderful ( similar to what the minimize currently does )

**Comment by Healix** [comment]
Do you actually want it to prevent exiting the program, or only when you press the X button? For example, if you were to ALT+F4 or right click the task bar button and select close window, it would hide the window instead. The only way to close the program properly would be to right click the tray icon and select exit.

**Comment by wharlox** [comment]
i'd say just the X button for now - (maybe alt-f4 prevtion could be another 'option')  ; my biggest thing is i hit the X button when i do not mean t.

**Comment by Healix** [comment]
You can find close to tray in the [current release](https://github.com/Healix/Gw2Launcher/blob/master/Gw2Launcher/bin64/Release/Gw2Launcher.exe?raw=true). There's also options to hide the close and minimize buttons under the style settings.
