### ISSUE TITLE
Question: Selecting GFXSettings.xml to use

### ISSUE THREAD

**Issue by ShepardAP3** [Healix/Gw2Launcher#296]
Hi, first time user. I would like to use the normal game launcher for my main account, and use GW2Launcher exclusively for my 10 alt accounts.  I would also like to use MINIMAL graphics settings on all my alt accounts but keep my settings as is for my main account. 

In the wiki it says:
To configure which GFXSettings.xml file to use, select Graphics under the Local.dat tab and browse for one. You may choose to either use one from an existing account, an existing file or you can create a new one. You may also modify the graphics settings here, or load one of the presets.

However when I go to Settings > Tools > Local.dat it doesn't show any graphic options or place to select which GFXSettings.xml setting to use. So I'm not sure how to set all of the accounts in the GW2Launcher to use a different xml file for the graphics.

I believe that my issue stems from using the features that let all the local.dat files to be handled together. But I'm just looking for some guidance on how to have all of the gw2launcher accounts use 1 xml file and then my main account that uses the normal GW2 exe use a different one. I'm hoping that I'm just missing one of the menus that has what I'm looking for.

![GW2Launcher settings](https://user-images.githubusercontent.com/131497443/233747478-ee7d7367-e172-4258-9e86-252bb49b722b.PNG)

Thanks for all your work!

**Comment by Healix** [comment]
It's under the account's settings. Right click an account > Edit > Local.dat > GFXSettings.xml.

**Comment by ShepardAP3** [comment]
I knew it must be something simple that I was missing. Thanks for the quick response!  Really appreciate your work on the wonderful tool
