### ISSUE TITLE
unable to build: missing formAccountAffinity

### ISSUE THREAD

**Issue by cpboyd** [Healix/Gw2Launcher#297]
I've cloned the repo and opened the solution with VS 2022, but there's an error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'formAccountAffinity' could not be found (are you missing a using directive or an assembly reference?)	Gw2Launcher	C:\Users\boyd\Documents\GitHub\Gw2Launcher\Gw2Launcher\UI\formSettings.cs	4200	Active
```
For this line:
https://github.com/Healix/Gw2Launcher/blob/master/Gw2Launcher/UI/formSettings.cs#L4200

**Comment by cpboyd** [comment]
Workaround: It appears like this function isn't used elsewhere, so it built when I commented out the function.

**Comment by Healix** [comment]
That was removed. I use a tool to automatically create a release build and delete any files I've marked as unused. I'm guessing I uploaded it prior to compiling it, which would have had the error on compile, then I would have removed those lines.

I re-uploaded it, including some minor changes.

**Comment by cpboyd** [comment]
@Healix thank you!
