### ISSUE TITLE
Integration with TacO

### ISSUE THREAD

**Issue by MinorMissDemeanor** [Healix/Gw2Launcher#30]
It seems that the most current build does not work with the newest TacO feature of multi-box overlay support.  Is this something that can be added?

http://www.gw2taco.com/2020/05/experimental-multibox-support.html

https://www.reddit.com/r/Guildwars2/comments/gssebo/taco_experimental_multibox_support/

**Comment by Healix** [comment]
To get TacO to work with multiple clients, you need to start it with the -mumble and -forcenewinstance options.

---

For the current version of Gw2Launcher, it has to be set per account:

Right click the account > edit. Under launch options, add the following argument (where X is a unique identifier, such as gw2mumble1 for account 1):
-mumble X

To start TacO, set the following for "run after launching", substituting your own information:
cd c:\path\to\TacO\folder
start GW2TacO.exe -mumble X -forcenewinstance

---

For the [beta version](https://github.com/Healix/Gw2Launcher/tree/master/Gw2Launcher/bin64/Beta) (64-bit), I added variable support to the launch arguments, so to get it to run on all accounts:

Right click any account > settings. Under launch options, add the argument:
-mumble gw2mumble%accountid%

For "run after launching":
cd c:\path\to\TacO\folder
start GW2TacO.exe -mumble gw2mumble%accountid% -forcenewinstance
