### ISSUE TITLE
Unable to automatically log in

### ISSUE THREAD

**Issue by FrozenPhantom** [Healix/Gw2Launcher#301]
Whenever I select my accounts to launch and log in, it opens the launcher and reads the correct .dat file to get the login info, but it never presses the ''Log In'' button so the game never starts and the other accounts don't launch becouse they are stuck waiting for the fist account to log in. I have to watch the entire process and hit ''Log In'' for each account or else it will just keep waiting endlessly.
In the past (I presume this was before the CoherentUI update) each account would launch and log in fine, and the other accounts would follow after the specified time had passed that I put in.

**Comment by Healix** [comment]
Are you using the [beta version](https://github.com/Healix/Gw2Launcher/blob/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe?raw=true)? It's currently required due to CEF. If you already are, ensure you haven't disabled automatic logins (right click > All/Selected > Disable automatic logins).

**Comment by FrozenPhantom** [comment]
I already had automatic logins enabled, but updating to the beta version seems to have fixed the problem, thanks!
