### ISSUE TITLE
CefHost.exe being launched from different temporary location every time

### ISSUE THREAD

**Issue by TheQuickFox** [Healix/Gw2Launcher#319]
Since a few days, every time I launch my second client I get a firewall popup asking if I want to allow

%appdata%\Roaming\Gw2Launcher\data\temp\2\gw2cache-{6501A8C1-4BAF-2A20-C2A8-0165AF4B202A}\CefHost.exe to connect to the internet. I allow this and the game starts, but the next time the code between the {} is different so my firewall asks again if CefHost.exe may connect to the internet.

Is there a way I can stop these dynamically generated different folders to be made every time I launch my second client?

GW2Launcher build 7195 release 19 date May 15, 2023

**Comment by Healix** [comment]
Settings > Tools > Local.dat > Allow the cache to be remembered and reused

The last patch changed CEF to prevent multiple clients from using the same CefHost.exe, which is why this is happening.

**Comment by TheQuickFox** [comment]
Awesome! Thank you very much for your quick solution. <3
