### ISSUE TITLE
Feature Request: Screen Grids

### ISSUE THREAD

**Issue by magnapeccatrix** [Healix/Gw2Launcher#32]
Hello I've been using Healix GW2 Launcher with my monitor's display software which comes preloaded with screen grid helper and I was wondering if developer can create similar feature for GW2 Launcher. It's very useful in arranging windows manually or automatically (Idk how I triggered that auto arrangement on grid template change, doesn't happen otherwise) I've recorded a short video. There are also some grid programs out there but making it part of GW2 Launcher would be great hence the reason I made this post.
https://www.youtube.com/watch?v=BTohGFEsqR8 (CTRL+Click to open in new tab)

**Comment by pro0digy** [comment]
This feature is already implemented :)

**Comment by Healix** [comment]
Is this something you're wanting to constantly change, or just set once and have it saved?

The tool Gw2Launcher already has allows for positioning multiple accounts simultaneously and having them snap together, it just doesn't have preset templates.

**Comment by magnapeccatrix** [comment]
Thanks for the replies, I'm looking for preset templates and windows to auto snap closest one when I drag them. Constant change wasn't something I wanted to show, I don't want it.

**Comment by Healix** [comment]
You can now find this feature under the menu when configuring the window size/position.

**Comment by magnapeccatrix** [comment]
Thank you @Healix I will check it when I could, I appreciate your responses to people requests all this time.
