### ISSUE TITLE
issue on Win 11 when selecting characters while +3 gw2 accounts launched

### ISSUE THREAD

**Issue by 2ool** [Healix/Gw2Launcher#329]
Hi,
Thanks for this great add-on which I was using on windows 10 flawlessly.
I just moved to win11 fresh install, and 1st thing I did copied all win10 drive gw2 "program files", "Gw2Launcher" and "Guild Wars 2" Roaming folders to their perspective new location on win11, so all settings and add-ons (GW2 Radial & arcdps) should work.

However, I run into issue that I can start all my 5 accounts just fine, but when I click a character to get-in for each account, all gw2 windows crashed.
I have tried all settings and suggestion I could find on here, but nothing resolve the issue. I have also tried to delete everything and start fresh GW2 and Gw2Launcher settings without any Add-ons, and still have the same issue.

I could have only run up to 3 accounts, and once I tried to run & enter 4th account character, some instance crashed and I ended up with 1or 2 game instances.

below is the crash report for 2 logs and some screenshots for the error (which sometimes they appear when it is crashed):

> *--> Crash <--*
> OOM: Heap, bytes=8388728
> App: Gw2-64.exe 
> Pid: 6220
> BaseAddr: 00007FF60EAD0000
> ProgramId: 101
> Build: 147095
> When: 2023-06-26T12:41:18Z 2023-06-26T15:41:18+03:00
> Uptime:   0 days  0:01:45
> Flags: 0
> DumpFile: Crash.dmp
> 
> *--> System <--*
> Name: 00cb6452
> IpAddr: 192.168.1.4
> Processors: 8 [GenuineIntel:6:14:3]
> OSVersion: Windows 10.0 (64 bit)
> 
> *--> System Memory <--*
> Physical:  4369MB/16325MB  26%
> Paged:       11MB/16325MB  0%
> Virtual:  134177533MB/134217727MB  3%
> Load: 73%
> CommitTotal:  16314MB
> CommitLimit:  16325MB
> CommitPeak:   16325MB
> SystemCache:   4950MB
> HandleCount:  89612
> ProcessCount:   163
> ThreadCount:   2370
> 
> *--> Process Memory <--*
> Private:         2599MB
> WorkingSet:      2169MB
> PeakWorkingSet:  2170MB
> PageFaults:   1397428
> 
> *--> Memory Category Usage (Inclusive) <--*
> [Category]              [Size(MB)]  [Count]     
> Root                    1960.06     756026      
> Programmer Data         1308.50     400139      
> Engine                  716.27      110704      
> Game                    415.60      207350      
> Uncategorized           393.95      327014      
> Gr                      375.88      51359       
> Model-Programmer        313.03      35946       
> Model Granny            309.02      16681       
> Content                 269.15      67779       
> Art Assets              228.34      14455       
> Gr Material             173.24      9380        
> DDI                     146.66      7443        
> Collections             118.64      16777       
> Dictionary              113.78      2191        
> Text                    106.77      14151       
> UI Assets               84.38       849         
> UI Textures             84.30       653         
> Anim Import Packfile    71.20       54          
> Anim Import Models      71.20       54          
> Character Models        59.85       4510        
> Composite Models        51.92       1634        
> Gr Umbra                40.11       1631        
> I/O                     37.85       989         
> Composite Tex Pool      37.15       152         
> 
> *--> Memory Category Usage (Exclusive) <--*
> [Category]              [Size(MB)]  [Count]     
> Uncategorized           393.95      327014      
> Model Granny            309.02      16681       
> Content                 269.15      67779       
> Gr Material             173.24      9380        
> DDI                     146.51      2722        
> Dictionary              113.78      2191        
> Text                    106.77      14151       
> UI Textures             84.30       651         
> Anim Import Packfile    71.20       54          
> Gr Umbra                40.11       1631        
> Composite Tex Pool      37.15       152         
> Archive                 36.47       39          
> Collide                 16.16       1764        
> Composite               16.10       2506        
> Composite Packfile      14.63       410         
> Audio FMOD              13.82       11384       
> Collide Havok           10.98       12137       
> Audio                   9.61        1260        
> Game Animation          8.75        67311       
> Character Packfile      7.21        9           
> Game                    6.18        37764       
> Terrain Geo             5.96        800         
> Frame                   5.51        83          
> CharClient              4.96        14397       
> 
> *--> DllList <--*
> 00007FF60EAD0000 - C:\Program Files\Guild Wars 2\Gw2-64.exe
> 00007FFEE7AD0000 - C:\Windows\SYSTEM32\ntdll.dll
> 00007FFEE6300000 - C:\Windows\System32\KERNEL32.DLL
> 00007FFEE5130000 - C:\Windows\System32\KERNELBASE.dll
> 00007FFEE5CD0000 - C:\Windows\System32\USER32.dll
> 00007FFEE4ED0000 - C:\Windows\System32\win32u.dll
> 00007FFEE5CA0000 - C:\Windows\System32\GDI32.dll
> 00007FFEE5620000 - C:\Windows\System32\gdi32full.dll
> 00007FFEE4F70000 - C:\Windows\System32\msvcp_win.dll
> 00007FFEE5010000 - C:\Windows\System32\ucrtbase.dll
> 00007FFEE6250000 - C:\Windows\System32\ADVAPI32.dll
> 00007FFEE6BD0000 - C:\Windows\System32\msvcrt.dll
> 00007FFEE59D0000 - C:\Windows\System32\sechost.dll
> 00007FFEE7250000 - C:\Windows\System32\RPCRT4.dll
> 00007FFEE5950000 - C:\Windows\System32\WS2_32.dll
> 00007FFEE4F00000 - C:\Windows\System32\WINTRUST.dll
> 00007FFEE7370000 - C:\Windows\System32\ole32.dll
> 00007FFEDF6B0000 - C:\Windows\SYSTEM32\VERSION.dll
> 00007FFEE2350000 - C:\Windows\SYSTEM32\WTSAPI32.dll
> 00007FFEE6C80000 - C:\Windows\System32\combase.dll
> 00007FFEDB670000 - C:\Windows\SYSTEM32\WINMM.dll
> 00007FFEE5B20000 - C:\Windows\System32\OLEAUT32.dll
> 00007FFEE63D0000 - C:\Windows\System32\SHELL32.dll
> 00007FFEE5740000 - C:\Windows\System32\CRYPT32.dll
> 00007FFEC9520000 - C:\Windows\SYSTEM32\MSACM32.dll
> 00007FFED6650000 - C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.22621.1778_none_57fe2016ce1542ec\gdiplus.dll
> 00007FFED5B90000 - C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_fb280a3c7926c2cc\COMCTL32.dll
> 00007FFEE2070000 - C:\Windows\SYSTEM32\USP10.dll
> 00007FFED6810000 - C:\Windows\SYSTEM32\MSIMG32.dll
> 00007FFEC4CD0000 - C:\Windows\SYSTEM32\Secur32.dll
> 00007FFEE46E0000 - C:\Windows\SYSTEM32\CRYPTBASE.DLL
> 00007FFEE4260000 - C:\Windows\SYSTEM32\SSPICLI.DLL
> 00007FFEE5C60000 - C:\Windows\System32\IMM32.DLL
> 00007FFEE4740000 - C:\Windows\SYSTEM32\MSASN1.dll
> 00007FFEE55A0000 - C:\Windows\System32\bcryptPrimitives.dll
> 00007FFED7730000 - C:\Windows\SYSTEM32\dbghelp.dll
> 00007FFEE2EE0000 - C:\Windows\SYSTEM32\windows.storage.dll
> 00007FFEE2DA0000 - C:\Windows\SYSTEM32\wintypes.dll
> 00007FFEE5FF0000 - C:\Windows\System32\SHCORE.dll
> 00007FFEE5C00000 - C:\Windows\System32\shlwapi.dll
> 00007FFEE4E00000 - C:\Windows\SYSTEM32\profapi.dll
> 00007FFEE4010000 - C:\Windows\SYSTEM32\kernel.appcore.dll
> 00007FFEE4B90000 - C:\Windows\SYSTEM32\DEVOBJ.dll
> 00007FFEE4BC0000 - C:\Windows\SYSTEM32\cfgmgr32.dll
> 00007FFEE2700000 - C:\Windows\SYSTEM32\dxcore.dll
> 00007FFEE2400000 - C:\Windows\system32\uxtheme.dll
> 00007FFEDE910000 - C:\Windows\SYSTEM32\cryptnet.dll
> 00007FFEE5FD0000 - C:\Windows\System32\imagehlp.dll
> 00007FFEE46F0000 - C:\Windows\SYSTEM32\CRYPTSP.dll
> 00007FFEE3F80000 - C:\Windows\system32\rsaenh.dll
> 00007FFEE48A0000 - C:\Windows\SYSTEM32\bcrypt.dll
> 00007FFEDE6B0000 - C:\Windows\SYSTEM32\drvstore.dll
> 00007FFEE47B0000 - C:\Windows\SYSTEM32\wldp.dll
> 00007FFEE4510000 - C:\Windows\SYSTEM32\gpapi.dll
> 00007FFEE7510000 - C:\Windows\System32\clbcatq.dll
> 00007FFEE4030000 - C:\Windows\SYSTEM32\ntmarta.dll
> 00007FFED6120000 - C:\Windows\system32\napinsp.dll
> 00007FFED6CE0000 - C:\Windows\system32\pnrpnsp.dll
> 00007FFEE4480000 - C:\Windows\System32\mswsock.dll
> 00007FFEE3AF0000 - C:\Windows\SYSTEM32\DNSAPI.dll
> 00007FFEE3A80000 - C:\Windows\SYSTEM32\IPHLPAPI.DLL
> 00007FFEE5B10000 - C:\Windows\System32\NSI.dll
> 00007FFEDC6F0000 - C:\Windows\System32\winrnr.dll
> 00007FFEC3CF0000 - C:\Windows\system32\wshbth.dll
> 00007FFED9460000 - C:\Windows\system32\nlansp_c.dll
> 00007FFEDDA10000 - C:\Windows\System32\fwpuclnt.dll
> 00007FFEDD040000 - C:\Windows\System32\rasadhlp.dll
> 00007FFEE5EA0000 - C:\Windows\System32\msctf.dll
> 00007FFED9A30000 - C:\Windows\SYSTEM32\textinputframework.dll
> 00007FFEE0520000 - C:\Windows\SYSTEM32\WindowsCodecs.dll
> 00007FFEC2F70000 - C:\Windows\system32\explorerframe.dll
> 00007FFECA970000 - C:\Windows\SYSTEM32\TextShaping.dll
> 00007FFE82690000 - C:\Program Files\Guild Wars 2\bin64\cef\libcef.dll
> 00007FFEE60F0000 - C:\Windows\System32\COMDLG32.dll
> 00007FFEDFDD0000 - C:\Windows\SYSTEM32\PROPSYS.dll
> 00007FFEE2580000 - C:\Windows\SYSTEM32\dxgi.dll
> 00007FFEC0770000 - C:\Windows\SYSTEM32\UIAutomationCore.DLL
> 00007FFED62B0000 - C:\Windows\SYSTEM32\OLEACC.dll
> 00007FFEC1090000 - C:\Windows\SYSTEM32\NETAPI32.dll
> 00007FFEE37B0000 - C:\Windows\SYSTEM32\HID.DLL
> 00007FFEE4580000 - C:\Windows\SYSTEM32\USERENV.dll
> 00007FFEB68D0000 - C:\Program Files\Guild Wars 2\bin64\cef\chrome_elf.dll
> 00007FFEE2690000 - C:\Windows\SYSTEM32\dwmapi.dll
> 00007FFEE0B70000 - C:\Windows\SYSTEM32\DWrite.dll
> 00007FFEE4870000 - C:\Windows\SYSTEM32\ncrypt.dll
> 00007FFED6320000 - C:\Windows\SYSTEM32\WINSPOOL.DRV
> 00007FFECE530000 - C:\Windows\SYSTEM32\dxva2.dll
> 00007FFEB6720000 - C:\Windows\SYSTEM32\d3d9.dll
> 00007FFEDB480000 - C:\Windows\SYSTEM32\urlmon.dll
> 00007FFEDF430000 - C:\Windows\SYSTEM32\WINHTTP.dll
> 00007FFEC8B60000 - C:\Windows\SYSTEM32\CRYPTUI.dll
> 00007FFEE1890000 - C:\Windows\SYSTEM32\credui.dll
> 00007FFEDF410000 - C:\Windows\SYSTEM32\dhcpcsvc.DLL
> 00007FFEDF030000 - C:\Windows\SYSTEM32\wevtapi.dll
> 00007FFEC6EC0000 - C:\Windows\SYSTEM32\WININET.dll
> 00007FFECC440000 - C:\Windows\SYSTEM32\ESENT.dll
> 00007FFECE770000 - C:\Windows\SYSTEM32\iertutil.dll
> 00007FFED5C50000 - C:\Windows\SYSTEM32\srvcli.dll
> 00007FFEE3A70000 - C:\Windows\SYSTEM32\netutils.dll
> 00007FFEE3CC0000 - C:\Windows\SYSTEM32\DSROLE.DLL
> 00007FFEDEFC0000 - C:\Windows\SYSTEM32\WKSCLI.DLL
> 00007FFEDC710000 - C:\Windows\SYSTEM32\SAMCLI.DLL
> 00007FFEE4830000 - C:\Windows\SYSTEM32\NTASN1.dll
> 00007FFEE4C30000 - C:\Windows\SYSTEM32\DPAPI.dll
> 00007FFEDF6C0000 - C:\Windows\SYSTEM32\dhcpcsvc6.DLL
> 00007FFEE3A00000 - C:\Windows\SYSTEM32\WINSTA.dll
> 00007FFEDCB90000 - C:\Windows\System32\MMDevApi.dll
> 00007FFEDC7A0000 - C:\Windows\SYSTEM32\mscms.dll
> 00007FFEE0170000 - C:\Windows\SYSTEM32\DSREG.DLL
> 00007FFEE3DE0000 - C:\Windows\SYSTEM32\POWRPROF.dll
> 00007FFEE3DC0000 - C:\Windows\SYSTEM32\UMPDC.dll
> 00007FFEE1DD0000 - C:\Windows\System32\CoreMessaging.dll
> 00007FFEE1870000 - C:\Users\2ool\AppData\Roaming\Gw2Launcher\data\temp\1\CB850469-1ED1-4DD2-B77D-78C36FF610B9\amd_ags_x64.dll
> 00007FFEDEDA0000 - C:\Windows\SYSTEM32\VCRUNTIME140.dll
> 00007FFED4E10000 - C:\Windows\SYSTEM32\nvapi64.dll
> 00007FFEE75C0000 - C:\Windows\System32\SETUPAPI.dll
> 00007FFEE0DE0000 - C:\Windows\SYSTEM32\d3d11.dll
> 00007FFEDF370000 - C:\Windows\SYSTEM32\directxdatabasehelper.dll
> 00007FFEDBA50000 - C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_675be35f1ba2315e\nvldumdx.dll
> 00007FFECEF30000 - C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_675be35f1ba2315e\nvwgf2umx.dll
> 00007FFECD260000 - C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_675be35f1ba2315e\Display.NvContainer\MessageBus.dll
> 00007FFEE1610000 - C:\Windows\SYSTEM32\dcomp.dll
> 00007FFEB8400000 - C:\Windows\SYSTEM32\winmmbase.dll
> 00007FFEB83B0000 - C:\Windows\SYSTEM32\wdmaud.drv
> 00007FFEDFC80000 - C:\Windows\SYSTEM32\AVRT.dll
> 00007FFEB83A0000 - C:\Windows\SYSTEM32\ksuser.dll
> 00007FFEC63C0000 - C:\Windows\SYSTEM32\AUDIOSES.DLL
> 00007FFEC9540000 - C:\Windows\SYSTEM32\msacm32.drv
> 00007FFEC9510000 - C:\Windows\SYSTEM32\midimap.dll
> 00007FFEE29A0000 - C:\Windows\SYSTEM32\resourcepolicyclient.dll
> 00007FFEBEFD0000 - C:\Windows\SYSTEM32\icm32.dll
> 00007FFEDE980000 - C:\Windows\SYSTEM32\CoreUIComponents.dll
> 
> [DbgHelp.dll is C:\Windows\SYSTEM32\dbghelp.dll]
> [DbgHelp.dll version 10.0.22621.1 (64/32-bit compatible)]
> 
> *--> ClientContextThreadProc Thread 0x22b0 <--*
> 
> *--> Trace <--*
> Pc                Rt                : Args
> 00007ff6`0eba607b 00007ff6`0eb9a14b : 00000000`00000000 00007ff6`0ed3c1f4 00007ff6`101143f0 00000000`00800078 
> 00007ff6`0eb9a14b 00007ff6`0ec95b41 : 00000221`a5a556b8 00000221`a5a55600 00000221`92006a70 00007ff6`0ec95d96 
> 00007ff6`0ec95b41 00007ff6`0ec965ac : 00000221`a5a55690 00000000`00000000 00000000`00000000 00007ff6`0eba98b9 
> 00007ff6`0ec965ac 00007ff6`0f736937 : 00000000`00000002 00000071`9edff700 00000000`00000000 00000221`00000002 
> 00007ff6`0f736937 00007ff6`0f732850 : 00000221`a049bee0 00000221`6f0eeca0 00000000`00000000 00000000`00002710 
> 00007ff6`0f732850 00007ff6`0f733847 : 00000000`00000000 00000221`a049bee0 01d9a82b`81409455 00007ff6`0fc276c5 
> 00007ff6`0f733847 00007ff6`0f728cd6 : 00000221`21486f80 00007ff6`00000008 00000000`00000002 00000000`00000008 
> 00007ff6`0f728cd6 00007ff6`0ef34ceb : 00000221`119c04f0 00000000`00000002 00000000`00000002 00000221`903408a0 
> 00007ff6`0ef34ceb 00007ff6`0edecc2c : 00000000`00000002 00000221`00000030 00000000`00000002 00007ff6`0ed2615e 
> 00007ff6`0edecc2c 00007ff6`0edeb1c0 : 00000000`00000000 00000221`119c4660 00000221`119c4660 00000221`119c4660 
> 00007ff6`0edeb1c0 00007ff6`0edeae2d : 00000019`0000000b 00000000`00000001 00000000`00000001 00007ffe`0000001b 
> 00007ff6`0edeae2d 00007ff6`0edec1b7 : 01d9a82b`81409455 00000000`00000000 00000000`00000000 00000000`00a5662f 
> 00007ff6`0edec1b7 00007ff6`0edec286 : 00000000`00a4c339 00007ff6`00000000 ffffffff`fffe7960 00000000`00000000 
> 00007ff6`0edec286 00007ff6`0edea595 : 00000221`119c4660 00000000`00000000 00000221`119c4660 00000000`00000000 
> 00007ff6`0edea595 00007ff6`0eb9c1e9 : 00000000`00000000 00000000`00000000 00000221`116e9500 00000000`00000005 
> 00007ff6`0eb9c1e9 00007ff6`0eda688a : 00000221`00000000 00000221`117b9500 00000000`00000000 00000000`00000000 
> 00007ff6`0eda688a 00007ffe`e63126ad : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
> 00007ffe`e63126ad 00007ffe`e7b2a9f8 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
> 00007ffe`e7b2a9f8 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
> 
> *--> Thread registers <--*
> rax=0000000000000eea rbx=0000000000000000 rcx=0000000000000000
> rdx=00000000ffffffff rsi=000000719edff450 rdi=0000000000000005
> rip=00007ff60eba607b rsp=000000719edfeeb0 rbp=0000000000000000
>  r8=0000000041000000  r9=0000000000000000 r10=00000000ffffffff
> r11=0000000000000000 r12=00000221aff0415a r13=0000000000000022
> r14=0000000000000000 r15=000000000000009b
> cs=0033 ss=002b ds=002b es=002b fs=0053 gs=002b efl=00000206
> 
> 
> *--> Code <--*
> 00007ff6`0eba605b  85c00f85 91000000 ff15afc5 55014889 ............U.H.
> 00007ff6`0eba606b  05a06f1d 02488d4c 2460ff15 a5c25501 ..o..H.L$`....U.
> 00007ff6`0eba607b  488b8424 58010000 4c8d0586 f8560148 H..$X...L....V.H
> 00007ff6`0eba608b  89442440 4885ff48 8b8424f8 00000044 .D$@H..H..$....D
> 00007ff6`0eba609b  8bcd4889 4424484c 0f45c748 8b842400 ..H.D$HL.E.H..$.
> 00007ff6`0eba60ab  01000048 8bd64889 4424508b cb488d44 ...H..H.D$P..H.D
> 
> *--> Stack <--*
> 00000071`9edfeeb0  00000221`0f540e00 00007ff6`10c6f0c0 00000221`0f714100 00000000`00000001 ..T.!............Aq.!...........
> 00000071`9edfeed0  00000071`9edfeef0 00000071`9edfef10 00000000`00000000 00000071`9edfeea0 ....q.......q...............q...
> 00000071`9edfeef0  00007ff6`0eba607b 00000071`9edfeeb0 00000000`00000000 00000000`00000000 {`..........q...................
> 00000071`9edfef10  00000000`fffffffa 00000000`00000000 00000071`9edff129 00000000`00000007 ................)...q...........
> 00000071`9edfef30  00000000`00000002 00000000`00000070 00009fbf`0010000f 0053002b`002b0033 ........p...............3.+.+.S.
> 00000071`9edfef50  00000246`002b002b 00007ffe`e516f122 00000221`00000000 00000000`00000000 +.+.F..."...........!...........
> 00000071`9edfef70  00000221`9a1f0860 00007ff6`0eb9a1c6 00000221`93c03200 ffffffff`fffffffe `...!............2..!...........
> 00000071`9edfef90  00000071`9edfef10 00000000`00000000 00000000`00000005 00000071`9edfeeb0 ....q.......................q...
> 00000071`9edfefb0  00000000`00000000 00000071`9edff450 00007ff6`10114400 00007ff6`10114400 ........P...q....D.......D......
> 00000071`9edfefd0  00000000`00000000 00007ff6`0ead0000 00000071`9edfedd0 00000221`aff0415a ....................q...ZA..!...
> 00000071`9edfeff0  00000000`00000022 00000000`00000000 00000000`0000009b 00007ff6`0eba607b ".......................{`......
> 00000071`9edff010  00000000`0000027f 00000000`00000000 00000000`00000000 0000ffff`00009fbf ................................
> 00000071`9edff030  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
> 00000071`9edff050  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
> 00000071`9edff070  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
> 00000071`9edff090  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
> 00000071`9edff0b0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
> 00000071`9edff0d0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
> 00000071`9edff0f0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
> 00000071`9edff110  00000000`3d4d4d7a 00000000`00000000 00000000`3d449ba6 00000000`00000000 zMM=..............D=............
> 00000071`9edff130  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
> 00000071`9edff150  00000000`00000000 00000000`00000000 00000000`3d449ba6 00000000`00000000 ..................D=............
> 00000071`9edff170  00000000`3d4d4d7a 00000000`00000000 00000000`00000000 00000000`00000000 zMM=............................
> 00000071`9edff190  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
> 00000071`9edff1b0  00000071`9edff230 00000000`00035436 00000000`001a5bd5 00035436`00000000 0...q...6T.......[..........6T..
> 00000071`9edff1d0  00000221`203ef06c 00000000`00000004 00000000`00000000 00007ff6`0ed328de l.> !....................(......
> 00000071`9edff1f0  00000000`00000005 00000000`00000001 00000000`00000000 00000221`937a07a0 ..........................z.!...
> 00000071`9edff210  00000000`00000000 00007ff6`0ebb5246 00000000`00000000 00007ff6`0ebb50df ........FR...............P......
> 00000071`9edff230  00000000`00006000 00000221`925c0978 00000000`00000000 00000221`aff00ba0 .`......x.\.!...............!...
> 00000071`9edff250  00000000`00000006 00007ffe`e7b0d19a 00000000`016200fc 00000000`00000020 ..................b..... .......
> 00000071`9edff270  00000221`38ded8b0 00000221`aff04154 00000000`00000001 00000000`00000000 ...8!...TA..!...................
> 00000071`9edff290  00000071`00000000 00000221`0f543180 00000000`00000002 00007ffe`e7b0d19a ....q....1T.!...................
> 
> *--> Error Logs (1)<--*
> : true
> 12:39:54Z 	Debugging Enabled: false
> 12:39:54Z New:
> 12:39:54Z 	Backend: CEF
> 12:39:54Z 	Dll Path: C:\Users\2ool\AppData\Roaming\Gw2Launcher\data\temp\1\gw2cache\libcef.dll
> 12:39:54Z 	Exe Path: C:\Users\2ool\AppData\Roaming\Gw2Launcher\data\temp\1\gw2cache\CefHost.exe
> 12:39:54Z 	Cookies Path: Ä‘Ä€
> 12:39:54Z 	Minidump Path: 
> 12:39:54Z 	Output Path: C:\Users\2ool\AppData\Roaming\Gw2Launcher\data\temp\1\gw2cache
> 12:39:54Z 	Client Script Hash: -1328522868
> 12:39:54Z 	Timeout: 40
> 12:39:54Z 	Async: true
> 12:39:54Z 	Cache Disabled: false
> 12:39:54Z 	Proxy Enabled: true
> 12:39:54Z 	Debugging Enabled: false
> 12:39:54Z New settings will be ignored!
> 12:40:07Z Failed to write user-preferences.
> 12:40:08Z The user closed the browser.
> 12:40:08Z The browser is being closed.
> 12:40:08Z We are requesting CEF close the browser when the user closed the browser.
> 12:40:08Z CEF is closing the browser.
> 12:40:09Z NULL REWARD TRACK: 2F919DCA-86D7-E111-BBF3-78E7D1936222
> 12:40:09Z NULL REWARD TRACK: 2F919DCA-86D7-E111-BBF3-78E7D1936222
> 12:40:18Z Texture missing mip chain: 0x00dd6d
> 12:40:19Z Texture missing mip chain: 0x01350d
> 12:40:21Z Texture '0x216075' dimensions too small
> 12:40:21Z Loading '0x216075' texture failed
> 12:40:21Z Texture '0x216076' dimensions too small
> 12:40:21Z Loading '0x216076' texture failed
> 12:40:21Z Texture '0x21606d' dimensions too small
> 12:40:21Z Loading '0x21606d' texture failed
> 12:40:21Z Texture '0x21606e' dimensions too small
> 12:40:21Z Loading '0x21606e' texture failed
> 12:40:21Z Texture '0x216071' dimensions too small
> 12:40:21Z Loading '0x216071' texture failed
> 12:40:21Z Texture '0x216072' dimensions too small
> 12:40:21Z Loading '0x216072' texture failed
> 12:40:22Z The user closed the browser.
> 12:40:22Z The browser is being closed.
> 12:40:22Z We are requesting CEF close the browser when the user closed the browser.
> 12:40:22Z CEF is closing the browser.
> 12:40:23Z Failed to write user-preferences.
> 12:40:50Z Failed to write GFE XML: 5
> 12:40:50Z Failed to write user-preferences.
> Crashed at 12:41:18Z
> 
> *--> Error Logs (2) <--*
> \temp\2\gw2cache\CefHost.exe
> 12:39:55Z 	Cookies Path: Ä‘Ä€
> 12:39:55Z 	Minidump Path: 
> 12:39:55Z 	Output Path: C:\Users\2ool\AppData\Roaming\Gw2Launcher\data\temp\2\gw2cache
> 12:39:55Z 	Client Script Hash: 731948500
> 12:39:55Z 	Timeout: 40
> 12:39:55Z 	Async: true
> 12:39:55Z 	Cache Disabled: false
> 12:39:55Z 	Proxy Enabled: true
> 12:39:55Z 	Debugging Enabled: false
> 12:39:55Z New:
> 12:39:55Z 	Backend: CEF
> 12:39:55Z 	Dll Path: C:\Users\2ool\AppData\Roaming\Gw2Launcher\data\temp\2\gw2cache-{EB2E5773-BE9A-2A49-7057-2EEB9ABE492A}\libcef.dll
> 12:39:55Z 	Exe Path: C:\Users\2ool\AppData\Roaming\Gw2Launcher\data\temp\2\gw2cache-{EB2E5773-BE9A-2A49-7057-2EEB9ABE492A}\CefHost.exe
> 12:39:55Z 	Cookies Path: Ä‘Ä€
> 12:39:55Z 	Minidump Path: 
> 12:39:55Z 	Output Path: C:\Users\2ool\AppData\Roaming\Gw2Launcher\data\temp\2\gw2cache-{EB2E5773-BE9A-2A49-7057-2EEB9ABE492A}
> 12:39:55Z 	Client Script Hash: 1465913402
> 12:39:55Z 	Timeout: 40
> 12:39:55Z 	Async: true
> 12:39:55Z 	Cache Disabled: false
> 12:39:55Z 	Proxy Enabled: true
> 12:39:55Z 	Debugging Enabled: false
> 12:39:55Z New settings will be ignored!
> 12:40:07Z Failed to write user-preferences.
> 12:40:10Z The user closed the browser.
> 12:40:10Z The browser is being closed.
> 12:40:10Z We are requesting CEF close the browser when the user closed the browser.
> 12:40:10Z CEF is closing the browser.
> 12:40:11Z NULL REWARD TRACK: 1E19467E-0650-E511-A22A-78E7D1936EF0
> 12:40:11Z NULL REWARD TRACK: 1E19467E-0650-E511-A22A-78E7D1936EF0
> 12:40:11Z Content is referencing a propID that doesn't exist propId='2248714043770673416'
> 12:40:11Z Content is referencing a propID that doesn't exist propId='1972964328275477224'
> 12:40:15Z Texture missing mip chain: 0x0f8c78
> 12:40:26Z Failed to write user-preferences.
> 12:40:31Z The user closed the browser.
> 12:40:31Z The browser is being closed.
> 12:40:31Z We are requesting CEF close the browser when the user closed the browser.
> 12:40:31Z CEF is closing the browser.
> 12:40:48Z Failed to write GFE XML: 5
> 12:40:48Z Failed to write user-preferences.
> Crashed at 12:41:49Z
> 
> *--> Graphics Device Info <--*
> VendorId    = 0x10de
> DeviceId    = 0x2484
> Version     = 53623
> Description = NVIDIA GeForce RTX 3070
> Compat      = 0x000000001f77fc3f
> VidMem      = 8192 MB
> 
> *--> NVidia Info <--*
> DriverVersion = 536.23

![Screenshot 2023-06-26 152331](https://github.com/Healix/Gw2Launcher/assets/58762073/8a2980ff-5b60-4129-92a4-cd7d5843c7f6)
![Screenshot 2023-06-26 153008](https://github.com/Healix/Gw2Launcher/assets/58762073/050d63f3-9188-4b0d-a42d-62ccf57193cb)

**Comment by Healix** [comment]
You're running out of memory. Each account is going to use around 3 GB just at the start (upwards of 5 GB if played), so 4 accounts is going to be near your limit, especially if you have other programs running. It's more likely to happen if multiple accounts are loading at the same time, when they're all wanting large chunks of memory now, vs waiting for them to load individually, allowing Windows to swap memory. When you do run out of memory, all programs that try to get more memory in that moment are going to crash.

You can't really fix this, you can only try to reduce your memory usage or get more memory. Ensure the accounts are on the lowest settings with the frame rate limited, and close any other programs with high memory usage (notably web browsers).

The screenshot is just arcdps intercepting the crash so you don't submit a log. The other is from something trying to launch a program named "fail" and it not existing, which I'm assuming is one of the addons.

**Comment by Healix** [comment]
You could try increasing the size of / manually configuring your page file (advanced system settings > performance settings > advanced). It should have been automatic, but the log shows it probably isn't, or Windows couldn't adapt it fast enough.

**Comment by 2ool** [comment]
You are right! setting page files to auto resolve the issue. Thank you!
it was odd that before changing the page files, the task manger was showing RAM usage slightly above 60%. But now when page files changed to auto, RAM almost full at 94%.
![Screenshot 2023-06-26 200721](https://github.com/Healix/Gw2Launcher/assets/58762073/285cbdcb-1fd4-4030-b283-66e5ee32c959)

**Comment by 2ool** [comment]
-
