### ISSUE TITLE
Editing multiple accounts at the same time

### ISSUE THREAD

**Issue by pro0digy** [Healix/Gw2Launcher#33]
Hey!
It would be really cool if we could select multiple accounts and edit their settings (only the relevant ones, settings that should be changed for each accound individually would be greyed out). Like assigning graphic settings profiles, sound options etc.

**Comment by Healix** [comment]
This is available in the latest version. When editing multiple accounts, you'll need to toggle which options you want to apply to all of them. By default, the toggle will enable when an option is modified; you can can right click it for more options.
