### ISSUE TITLE
Auto-Login no longer working after changing settings

### ISSUE THREAD

**Issue by trashcandrummer** [Healix/Gw2Launcher#330]
I tried to set up an additional account and tried out some settings but was sure the settings are again as was and I can't figure out why I still run into the following issue:

If I click on any of my (previously working) accounts, the login client opens, the mail is inserted, afterwards the password is inserted and then the mail is selected with the log text "Login entry complete" appearing.
Full log here: [log.txt](https://github.com/Healix/Gw2Launcher/files/11916374/log.txt)

Previously the Launcher automatically forwarded an ENTER to login (as far as I can see in the implementation on GitHub) yet it does not work any longer. I have to manually press "login" so the process can continue with pasting the authenticator key (which does work after I click "login" manually).

I honestly can't figure out why this automatic sending of ENTER would no longer work.
Based on the implementation there are three IFs here: https://github.com/Healix/Gw2Launcher/blob/master/Gw2Launcher/Client/Launcher_Autologin.cs#L1295 (up until line 1307)
Maybe one condition is true and this is why the process does not reach the point to send ENTER?

Would be great if you could help me out on what to test/check or even just adding more log messages so I can myself debug further.
Thanks a bunch!

Additional note: I previously tested with build 7195 yet updated just to verify: New version also does not help to get it working again.
And yes, the checkbox "Automatically enter email/password and login" is ticket ofc :)

**Comment by Healix** [comment]
Did you disable automatic logins? Right click any account > Selected/All > Disable automatic logins. That causes it to enter the email/password, but not login.
