### ISSUE TITLE
Trying to figure out how Authentication works

### ISSUE THREAD

**Issue by Alex1016182** [Healix/Gw2Launcher#332]
I have a lot of accounts and even with a lot of throttling I am frequently bumping into the anti-DDOS system. Using a VPN I can log into the remaining accounts without waiting, however I have to always manually authenticate them. I've noticed that there seems to be automatic 2FA on the launcher, but I can't figure out how to set it up, and I didn't find much help in the wiki either unfortunately. Does anyone use it and if so, is there a way to entirely automate the login process when changing IP with a VPN?

**Comment by Healix** [comment]
The account has to be using an authenticator:

https://help.guildwars2.com/hc/en-us/articles/230673087

To have it automatically enter the code, you add the authenticator key to the account's security settings (Edit > Security) and enable the option to automatically enter the code.

**Comment by Alex1016182** [comment]
Thank you so much! Now it's perfect!
