### ISSUE TITLE
Password is not being entered for 1 specific account

### ISSUE THREAD

**Issue by Fofeee** [Healix/Gw2Launcher#334]
Build 7254. Re entering the password in the options fixes it but after closing gw2launcher the problem returns almost as if it isnt being saved. Even after deleting the acount and re adding it the password is not being entered. The 8 other accounts I have on the launcher are working normally.

**Comment by Healix** [comment]
Does it look like the password is saved after restarting ("change password"), or is it empty?

If it appears saved, try exporting the password. Settings > Backup > Export. Select the password, choose to export in plain text and select the account. Open the exported file in notepad and verify what the password is. The password will be blank if it couldn't be decrypted.

If it's empty, under the security tab, set the password to something simple ( a ) and set the authenticator key to aaaaaaaaaaaaaaaa (if you already have a key set, you can toggle the option to automatically enter the code instead). OK, then open the settings back up to confirm it's still set (an invalid key won't save), then restart Gw2Launcher, and confirm if it's still set. If there's a bug preventing it from saving, none of the changes would have saved. Assuming it saved, repeat using your password to confirm it still doesn't save - try to figure out which character in your password is the problem.

**Comment by Fofeee** [comment]
Deleting the last character of the password (the number 1) appears to have fixed the issue. I tried a few other different passwords and they all worked as long as they didnt end in '1'. Very curious indeed. I appreciate you swift response. This launcher is a godsend for GW.

**Comment by Fofeee** [comment]
Deleting the last character of the password (the number 1) appears to have fixed the issue. I tried a few other different passwords and they all worked as long as they didnt end in '1'. Very curious indeed. I appreciate you swift response. This launcher is a godsend for GW.
