### ISSUE TITLE
Trying to move everything on 2nd screen, "Apply to all accounts" doesn't seem to work

### ISSUE THREAD

**Issue by Alex1016182** [Healix/Gw2Launcher#337]
I want the accounts to launch on my 2nd monitor, possibly with the initial launcher too which is always the middle of my 1st monitor. However, if I select a bunch, even if I select "apply to all accounts" it seems to only apply to the original one I clicked. I also tried to set up Auto-Arrange following a template, but I can't get that to work either - on the Launch options I click the ... button, then select the template I'd like and also select Auto Arrange -> Use Template and Save. I'm pretty sure it's something I'm doing wrong, but I can't figure it out

**Comment by Healix** [comment]
The apply all for windowed mode when editing multiple accounts is misleading. Enabling windowed mode is a part of the window options, so the box next to the size only applies the size, while the box below applies everything else.

To edit multiple multiple window sizes at once, ... > right click the window > Show other accounts > Choose which accounts you want to see. To save, right click > Save all.

The other way of using templates is to right click any account > Tools > Window manager. You can create account templates under the Manager tab, which are window templates (Templates tab) that can be assigned to accounts. Activating an account template will override the position/size of windowed accounts it applies to.

**Comment by Alex1016182** [comment]
> To edit multiple multiple window sizes at once, ... > right click the window > Show other accounts > Choose which accounts you want to see. To save, right click > Save all.

This seems to open lots of windows and then the program crashes. Templates seems great, but is there a way to make it the default without having to open the templates tab and activate it before launching?

**Comment by Healix** [comment]
You can select which accounts you want it to show. By default, all accounts set to windowed mode are automatically selected. It would definitely crash if you tried to show an excessive number of accounts.

Active templates will remain active until deactivated or modified. If you activate it and restart Gw2Launcher, it should still be activate.

**Comment by Alex1016182** [comment]
> You can select which accounts you want it to show. By default, all accounts set to windowed mode are automatically selected. It would definitely crash if you tried to show an excessive number of accounts.
> 
> Active templates will remain active until deactivated or modified. If you activate it and restart Gw2Launcher, it should still be activate.

Thanks a lot! For the most part the templates work great, but I've noticed sometimes they seem to stop working until you cancel the launches and try again. It seems to definitely do it when there isn't a space on the template anymore - is there a way to allow them to stack behind each other?

**Comment by Healix** [comment]
Templates will block launches if there's no room available. You can disable that under the options (manager tab). Disabling it will cause further accounts to launch without using the template (they'll use what's set under the account).

If you want the template to stack, under the manager tab, right click the template > Edit. Right click the window > Save as > New assigned template. You can activate multiple templates and they will be filled in the order they were activated in.

**Comment by Alex1016182** [comment]
Perfect! One final question on the matter: Is there a way you can make the launcher (Log in page) also appear on a chosen screen? It always defaults to my primary one

**Comment by Healix** [comment]
I could only move it after the login is shown, since it resets to the primary screen at that point.

Per account or just in general? I could have a launch option to position where the launcher should be, rather than simply centering it on a screen.
