### ISSUE TITLE
July 18 patch issues (Play button, email/password empty)

### ISSUE THREAD

**Issue by berdandy** [Healix/Gw2Launcher#339]
The option to use the large "Play" button on the login screen (with email/password) does not appear to be working after the latest patch. Using the auto-play 5s timer does function as a workaround but slows things down. I attempted to use -usecoherent in case that was related, but I'm not sure if that argument actually does anything any more. Regardless, the argument had no effect.

Additionally, this may be unrelated to the patch, but the email/password fields also suddenly stopped populating. However, recreating my "data" folder got that working again. I simply renamed it and let gw2launcher rebuild it. No errors in logs.

**Comment by Kawsmecal** [comment]
It did this to me all I had to do was reenter my information in the settings for the profile and it worked again.

**Comment by Healix** [comment]
CoherentUI was disabled in the patch, so -usecoherent does nothing now. DX9 is also gone.

Do you mean the option to automatically "play" isn't working? Open the log and launch an account. The final log entries related to automatic logins are "Login entry complete" (login is entered) and "LauncherCefLoginEvent" (ready to play). If you're seeing these and it's not playing, Settings > Guild Wars 2 > Tweaks > Launcher coordinates. Either ensure it's not been manually set, or ensure it's accurate.

**Comment by berdandy** [comment]
I had a chance to retest.  Indeed, the launcher coordinates tweak was checked. I don't recall doing that, but stranger things have happened.

It's possible that also caused the field issue because I did notice that when I reset the "data" dir, the resolution of the launcher changed. It's feasible that misalignment of some things could occur.

Anyways, all working now with a plausible cause, closing this. Thanks!
