### ISSUE TITLE
Gw2Launcher is changing my main client resolution

### ISSUE THREAD

**Issue by blackr4bbit** [Healix/Gw2Launcher#346]
My main client is starting at windows mode always after i use the Gw2Launcher, how can i solve this? that not a thing that happen sme time before, the Gw2Launcher not suppose to reconfigure my game resolution on my main client.

**Comment by Healix** [comment]
The account is either using the default GFXSettings.xml file that GW2 uses, or you're using basic mode.

For basic mode:

Settings > Guild Wars 2 > Management. If it's set to basic mode, all accounts will launch using the same folder Guild Wars 2 uses for settings. In this case, the account isn't changing GW2's settings, but rather GW2 is using the account's settings. There's an option to reset it when all accounts are closed.

For GFXSettings.xml:

Right click the account > Edit > Local.dat > Graphics. Look near the end of path for either "Guild Wars 2" or "Gw2Launcher". If it's "Guild Wars 2", the account is sharing the default file with GW2, so give a different file.

**Comment by blackr4bbit** [comment]
> The account is either using the default GFXSettings.xml file that GW2 uses, or you're using basic mode.
> 
> For basic mode:
> 
> Settings > Guild Wars 2 > Management. If it's set to basic mode, all accounts will launch using the same folder Guild Wars 2 uses for settings. In this case, the account isn't changing GW2's settings, but rather GW2 is using the account's settings. There's an option to reset it when all accounts are closed.
> 
> For GFXSettings.xml:
> 
> Right click the account > Edit > Local.dat > Graphics. Look near the end of path for either "Guild Wars 2" or "Gw2Launcher". If it's "Guild Wars 2", the account is sharing the default file with GW2, so give it a different file.

Thank you very much, its work with the GFXSettings method =)
