### ISSUE TITLE
Key combinations accidentally happen

### ISSUE THREAD

**Issue by bluenote73** [Healix/Gw2Launcher#348]
While launching, if I tab out to another window and use, say, escape, then windows grabs the keystrokes and brings up the start menu. I think (from my limited experience using AHK) that keystrokes can be directed to a particular window to prevent this from happening. This is during the logon phase, so I assume there's some use of ctrl (being held for a moment?) for some reason. This could be an enhancement or it could be a bug :)

**Comment by Healix** [comment]
GW2 uses the current state of the modifier keys, so I can't simply tell only GW2 that the key is pressed.

The reason ctrl is held is to use the clipboard, which I use to verify that GW2 is responding when entering the email and password. You can change it to not use the clipboard under Settings > Guild Wars 2 > Tweaks > Change how the email/password is entered, but it won't be able to retry if it fails.

**Comment by bluenote73** [comment]
Thanks :)

**Comment by bluenote73** [comment]
.
