### ISSUE TITLE
network authotization has stopped working

### ISSUE THREAD

**Issue by dameischta** [Healix/Gw2Launcher#35]
At login, suddenly guild wars asks me to enter the authentification code.
(this did work several days ago)

- all accounts have the correct username & password
- all of them have thier goolge auth code ... it even shows me the correct current & next code in the account security tab
- in global options -> security, all 3 checkboxes are set (network autorization: enable, remove & cancel launchung)
- (firewall is off ... just for testing :-))

**Comment by Healix** [comment]
Right click any account > tools > re-authenticate on next launch. If your IP changes regularly, authentication should be set to automatic under settings > security.

**Comment by dameischta** [comment]
account > tools > authenticate on next launch does work :-)

But it seems I have an issue with 'automatic authentitication'  (this was even enabled already). It's enabled ... but gw2 wants me to enter the code.
Looks like Gw2Launcher thinks I am already authenticated (for whatever reason).
Maybe you can add an option to force the autentication on every login?

**Comment by Healix** [comment]
Gw2Launcher probably failed to connect, which causes it to skip the authentication check for that launch. It's also limited to how often it checks, so if it checks and passes, then your IP changes, it won't check again for 10 minutes.

Requiring authentication on every launch (as well as aborting on a failed connection) is already done and will be available in a few weeks (the next update will have a lot of major changes).

**Comment by dameischta** [comment]
> Requiring authentication on every launch (as well as aborting on a failed connection) is already done and will be available in a few weeks (the next update will have a lot of major changes).

oh :-)  then i just wait until the new version is released
