### ISSUE TITLE
Daily acquisition of Astral on multiple instances

### ISSUE THREAD

**Issue by Ultimatorum** [Healix/Gw2Launcher#356]
Greetings community,

I have been using this app for a very long time and nothing but respect for all your hard work and dedication.
I am not sure if this question was asked before, i am not that much into development myself so i will shoot it as new thread.
When I launch multiple instances of the game, I am unable to open a trading post on each of them. The same happens with Astral daily. If I start 4 accounts at the same time (4 instances) I can still open only one at a time, while id have to restart other instances. This basically means that I have to start one instance, take daily, shut it down and then repeat the same for each individual account, which delays the collection of daily rewards marginally. 
Is there any option that I am not aware of in order to successfully run 4 or more instances at once while still being able to open daily Astral (Trading post) on each one?

Thank you for your time and patience,
Goran

**Comment by Healix** [comment]
If you close and re-open the BLTC/vault, it should load. I have this rarely happen when only playing 1 account, sometimes even after I had previously used the BLTC.

I don't think it's possible to entirely prevent it, but here's 2 things you can try.

GW2 doesn't allow CEF to be used by multiple accounts at a time. When you launch a second account, it will fail to start CEF and will create a new copy of CEF for itself. This shouldn't be a problem, but it does slow it down, as it ends up copying around 300 MB on launch, and again when you click play. 

Settings > Guild Wars 2 > Management. Enable localized execution set to full, which will give each account its own GW2 folder. Below that, enable the option to rename CEF on launch, which prevents GW2 from creating an extra copy of CEF for no reason.

If it's still a problem, Settings > Guild Wars 2 > Management. Enable deleting the web cache on account exit. This would only apply to your second launch of each account, so to delete it now, right click any account > Tools > Advanced > Delete cache folders > Delete cache.

**Comment by Ultimatorum** [comment]
When i start 4 accounts, only first one that i started is able to enter TP and Vault. Other accounts get error when i start opening TP and game crashes, but Vault just opens in a window and doesnt show option to claim daily 5. |

I did first step you adviced: Settings > Guild Wars 2 > Management. Enable localized execution set to full, which will give each account its own GW2 folder.

But i can not find other two. Sorry, can you be more precise (Below that, enable the option to rename CEF on launch, which prevents GW2 from creating an extra copy of CEF for no reason. If it's still a problem, Settings > Guild Wars 2 > Management. Enable deleting the web cache on account exit.)

**Comment by Healix** [comment]
You need to [update](https://github.com/Healix/Gw2Launcher/blob/master/Gw2Launcher/bin64/Release/Gw2Launcher.exe?raw=true) (build 7254). Those options were added in the June build.

**Comment by Ultimatorum** [comment]
Didn't see it in "Releases" section, my mistake. I have it now and will setup everything as explained. After i try it, i will replay here.

Thank you for your time

**Comment by Ultimatorum** [comment]
Just to report that everything works perfectly. Thank you again for all the help!
