### ISSUE TITLE
Issue opening 6 clients at once. Suggestion: group launch

### ISSUE THREAD

**Issue by SullieLore** [Healix/Gw2Launcher#36]
Hi,

When I launch 6 clients at the same time only 5 get to the character screen, the last always says "gw2 encountered an error" or such. Then I need to close the 6th client, wait a few seconds, and launch it again. Could you please add an internal cooldown for launching so many clients? I don't want to use the delay option because that will impact the time it takes to launch all clients (the first 5 works fine).

Also, it would be great if you could bundle several clients together so they launch as a set. For instance, I'd like to launch 6 clients with 1 click. Please consider adding this feature.

Thanks for the great app!

**Comment by Healix** [comment]
There is a limit to how often you can login and it worsens as you make attempts. It seems to be something like 4 accounts, then 1 every 15 or so seconds (you'll notice it takes longer to login) and it seems to persist until you to stop. If you try to force it and keep trying, you'll start seeing a 3005 error code and be locked out for around a minute.

The simplest thing I could do is add an option to only enable the delay after launching X number of accounts.

To quickly launch a group of accounts (assuming they're in order), right click and drag to select them, then launch. To launch a group with 1 button, you can use a shortcut (Gw2Launcher.exe -l:uid:1 -l:uid:2 etc).

**Comment by SullieLore** [comment]
Thank you. Never realised about the right click+drag, very helpful!

**Comment by Healix** [comment]
You'll find the option to limit launches under settings > general > launching in the latest version - it can be set automatically or manually.
