### ISSUE TITLE
Blish icon occupies Black Lion icon space on reinstall

### ISSUE THREAD

**Issue by Kawsmecal** [Healix/Gw2Launcher#365]
Had to reinstall Blish with GW2launcher when making some changes and everything is setup the way it's told to before as I followed the same guide, but it seems that Blish isn't moving over to make room for the new Wizard Vault icon that was added so now they occupy the same spot as the trading post/gem store icon button.

**Comment by Healix** [comment]
Old versions of Blish will have this problem. [1.1.1](https://blishhud.com/) is the current version.

**Comment by Kawsmecal** [comment]
> Old versions of Blish will have this problem. [1.1.1](https://blishhud.com/) is the current version.

But it's the same files as I had when it was updated? IDK how it would have not updated and won't update?

**Comment by Kawsmecal** [comment]
IDK what it was but launching Blish alone was making it overlay fine, but the mumblelink thing in GW2launcher made it overlay on top of the gem store. Same Blish files and I checked it was pointing at the same place so not double install or anything but replacing the files again with 1.1.1 again made it remember where to go I guess idk why. Oh well it's fixed weird issue tho.
