### ISSUE TITLE
Only 1 account of 4 autologins & autoplays

### ISSUE THREAD

**Issue by WhoBobber** [Healix/Gw2Launcher#368]
I recently had a power surge that fried my computer & the backup drive that  it was backing up to, so I am setting up the new computer and GW2Launcher from scratch. Got the GW2Launcher beta installed & trying to get my 4 GW2 accounts added to it. My main account goes all the way to the character selection screen just fine, but all 3 of the alt accounts stop with the cursor in the password field. The passwords are being entered because all I have to do is click on login (without entering anything in the password field) & then it proceeds all the way to the character selection screen. What can I do to get the 3 alt accounts to work as the main does?

Thanks for all your work on this app over the years.

**Comment by Healix** [comment]
Is Gw2Launcher entering the logins, or are they set to be remembered by GW2?

If they're remembered by GW2, you have to enable the option to "automatically login when remembered" under the account's launch options.

If they're entered by Gw2Launcher, it will automatically login by default unless it thinks it's failing to successfully enter the email/password. For more information, right click any account > Tools > Log and launch one of the accounts that fails to login.

**Comment by WhoBobber** [comment]
It was being remembered by GW2 and enabling that setting on 1 account did the trick for all 3 that weren't working. Thanks for your fast reply.
