### ISSUE TITLE
Network Authentication doesn't work

### ISSUE THREAD

**Issue by kxnrls** [Healix/Gw2Launcher#37]
For my account i've setup 2Factor Authentication with a OTP.
Showing the current otp in the security settings works fine, but it doesn't get automatically entered in the Launcher.

Regards

![image](https://user-images.githubusercontent.com/48994057/93749624-7fa2e880-fbfa-11ea-9b87-8239b9d15ac5.png)

**Comment by Healix** [comment]
Right click any account > tools > re-authenticate on next launch

Note that it doesn't enter the code into the launcher itself, it works in the background and only applies when it detects a change in your IP, which is checked on launch and only once every several minutes (if set to automatic). There are a few cases where it won't be able to tell if your IP has changed, in which case it skips it and you have to use the above.

It also has to be enabled under the general settings. Right click any account > settings > security > enable network authorization, and automatic

**Comment by kxnrls** [comment]
So im not sure if the problem is that it doesn't detect the ip change (Im using a VPN, so that might be a problem).
But even if i use "Tools -> Network authentication -> Authenticate on next launch" it doesn't work and the launcher still asks for a code.

And yes I have it enabled in the general settings.

**Comment by Healix** [comment]
I'm assuming your VPN is configured per application? Gw2Launcher also needs to be using it, otherwise it's authenticating your real IP.

**Comment by good-live** [comment]
The VPN is system wide. How long is the interval in which the ip is changed?
