### ISSUE TITLE
Question about automatic email input

### ISSUE THREAD

**Issue by Zaerienne** [Healix/Gw2Launcher#373]
I would like not the launcher not to use the clipboard to input account emails, but I'm unsure what "characters via post" and "characters via send" mean. 
What do those entail and is there a downside to changing to one of those?

**Comment by Healix** [comment]
Send sends 1 character at a time and has to wait for GW2 to respond to each character. It's slower and you can watch it being entered.

Post sends all of the characters at once and GW2 accepts it whenever it can.

Use post. Post is used by default when entering the password and for the email if the clipboard isn't available. The only advantage send has over post is it'll pause if GW2 freezes while entering the email/password, whereas post only waits 500ms.

The downside of not using the clipboard is there's no verification. Post/send is blindly entering the login, so if it fails, it won't know.

**Comment by Zaerienne** [comment]
Thank you so much for the thorough explanation!
