### ISSUE TITLE
No Playback sound when launching 

### ISSUE THREAD

**Issue by OhKeey** [Healix/Gw2Launcher#374]
Hi,

first of all I want to thank you for such an awesome tool, I think we all really appreciate it! :)

Unfortunately I ran in some kind of error which I'm not able to resolve myself. Whenever I start the game, I have no auto what so ever. Every time i need to swich mich playback device to some other one and after that back to normal to get any  sound. Also since the last update I guess - I have to crank the volume up to at least around 50 percent to get decent volume whereas before, I got my ears blown out at volume 10 xD.

Hope it help and maybe you have a solution.
Greetings!
![Bild_2023-10-15_013857889](https://github.com/Healix/Gw2Launcher/assets/120432256/c53a7b47-5659-48c7-b8d3-375236904f1b)
![Bild_2023-10-15_013908614](https://github.com/Healix/Gw2Launcher/assets/120432256/22c9a9ca-a145-48b0-9312-e1ae3eff31d5)
![Bild_2023-10-15_013925462](https://github.com/Healix/Gw2Launcher/assets/120432256/43e2d527-fb0a-4e83-9607-25daf53a303b)

edit: and I'm not able to change the language to english which sucks xD

**Comment by Healix** [comment]
If you want to change the settings, you need to right click the account > Selected > Launch (normal), otherwise GW2 won't save any changes.

For the volume, keep in mind it can be set in multiple places - under GW2's settings, the speaker volume in Windows, under the volume mixer in Windows and if available, on the actual speakers. Gw2Launcher can also change the volume (of the volume mixer) under Settings > Guild Wars 2 > Launch options, or Edit > Launch options.

**Comment by OhKeey** [comment]
I've tried that already. Yes it'll keep the setting if I launch it normally but nevertheless I need to switch it basically "off and on" to get the sound from guild wars (reselecting it without making any further changes)

**Comment by Healix** [comment]
Under the launch options (Edit > Launch options, and Settings > Guild Wars 2 > Launch options), there's an option to mute the game. Ensure mute all hasn't been enabled. Also ensure you haven't added -nosound to the launch arguments. These options will cause GW2 to start without sound and changing the audio device will unmute it.

**Comment by OhKeey** [comment]
It had something to so with my audio source. Everything in the launcher was set up correctly. Thank you anyways :)
