### ISSUE TITLE
Email and Password autofill still broken?

### ISSUE THREAD

**Issue by achen4** [Healix/Gw2Launcher#377]
I just downloaded it today for first time use. None of my accounts seem to be filling the email and password. All of the current posts about this issue seem to point to an old beta version of the launcher where it was fixed. Can't imagine I'm the only one with this issue or that I'm the first to discover it. Perhaps PEBKAC?

Using Build 7338

**Comment by Healix** [comment]
There are 2 options to automatically login. 1 has you enter your email/password into Gw2Launcher, the other is remembered by GW2. If you want Gw2Launcher to enter your email/password, ensure the option "automatically enter email/password and login" is enabled and the email/password isn't blank.

Holding alt/shift/ctrl will prevent the login from being entered.

If it's your first time, this shouldn't apply, but ensure the launcher coordinates haven't been modified. Right click any account > Settings > Guild Wars 2 > Tweaks. Improper coordinates will break it.

Right click any account > Tools > Log. Launch an account. The log should show what it's trying to do.

**Comment by achen4** [comment]
Thanks for this! I was digging around some more to find the "automatically enter email/password" and found that there are two places where you can enter the email and password in GW2launcher hence the confusion.

1. Right Click Account > Edit > Security 
2. Right Click Account > Edit > Launch Options (this is where you can see the check boxes for Automatically Enter email/password and login")

It seems I was using 1 and not 2 hence the issue. That makes me wonder why we have option 1. Is it for something else? Old code not cleaned up?
