### ISSUE TITLE
Compact trading post mode is not saved

### ISSUE THREAD

**Issue by Ne0kkk** [Healix/Gw2Launcher#381]
The compact trading post mode that is accessed by entering "I am Evon Gnashblade" in the search field is not saved anymore and has to be entered everytime an account is launched, which is a bit annoying. Before Anet switched to Chromium, it worked fine. With the normal launcher it still works fine and is saved.

**Comment by Healix** [comment]
CEF has this setting stored along with the 2FA reminder, which Gw2Launcher clears on every launch. If you want it to save, you will need to give the account an authenticator and use the [beta version](https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe). Right click the account > Edit > Security. You can set the authenticator to AAAAAAAAAAAAAAAA if you're using SMS.

Note this setting is stored under gw2cache, so patches and any of the options to clear the cache will reset it.

**Comment by Ne0kkk** [comment]
Thanks, that worked when launching normally. Clearing after a patch happens with the normal browser as well, so that's no problem.
