### ISSUE TITLE
Passwords will not be imported after Backup

### ISSUE THREAD

**Issue by Caliban2017** [Healix/Gw2Launcher#382]
Hello, 

is there a way to import a Backup of GW2 Launcher which includes the Account Passwords? What i did to Backup the Data is i choosed a Single File and include the GFXSettings.xml. After reinstallation of a fresh Windows i wanted to import that File again, which works fine, all Accounts are there with Daily Progress etc. But on all Accounts the Login Credentials are missing? I had to enter again every Password for every single Account.

When i try to import a backup of the XML Accounts, the Accounts will be imported but the Settings are missing like Daily Progress.

Is there a way to backup all account passwords into the Single File Backup?

Thanks and Greetings!

**Comment by Healix** [comment]
Passwords stored by Gw2Launcher? Passwords are by default encrypted to your user account, so if your user changes, the passwords can no longer be decrypted. When you create a backup, it'll show a warning with a link to change the encryption. It must be set to either portable or unencrypted to transfer it, whereas user only works on the current account, and PC only works on the current install of Windows.

Passwords remembered by GW2? GW2 encrypts your password to your user account, so if your user changes, the password will be blank.

**Comment by Caliban2017** [comment]
Okay that makes sense, i ignored this and it was for sure set to User. So of course this will not work to restore the Passwords after a Windows reinstallation. Thank you for the Explanation. So next time i should switch to PC Encryption and after a new installation of the OS it should be able to restore all Passwords.
