### ISSUE TITLE
Transfert launcher to a new computer

### ISSUE THREAD

**Issue by lucephile** [Healix/Gw2Launcher#384]
Hello,

Quick explain : 
My SSD crashed and I needed to install a new OS and in consequence a new GW2Launcher
I've lost my previous GW2launcher datas so far.

My accounts got the authentificator set up with the previous GW2Launcher configuration.

how can I activate the authentificator with the new configuration ?

Other question : 
I will run a software to gather data on my old SSD. If I manage to gather some files what are the important files to transfer to the new configuration?

Have a nice day

**Comment by Healix** [comment]
Do you mean - how do you recover the authenticator key? If you didn't keep a copy of it, you can't. You'll need to contact support to remove the authenticator if you're unable to recover it.

%appdata%\Gw2Launcher\settings.dat is where all settings are stored. If you can recover it, make a copy of it (keep a backup) and place it in the same location on the new drive, then start Gw2Launcher. This is only the way you can recover the authenticator keys if you didn't keep a copy. Note passwords will be lost, as they're encrypted by default to the user.

There are also backups of settings.dat under %appdata%\Gw2Launcher\backups

Local.dat and GFXSettings.xml can be found under the data folder, but they're not really important. Note passwords remembered by GW2 will be lost, as they're encrypted to the user.

**Comment by lucephile** [comment]
Thank you for your help

I've manage to recover the setting.dat file
the authentificator seems to work again now

I will check if i can dig some additional files

Thank you for your help

have a nice day
