### ISSUE TITLE
Launcher Folder now 729GB!

### ISSUE THREAD

**Issue by z-z00** [Healix/Gw2Launcher#385]
My launcher folder has exploded into 729GB! Each launcher file is 66GB! I'm not sure what settings I have wrong.
![image](https://github.com/Healix/Gw2Launcher/assets/151807653/e2b9befa-76eb-4b2e-8ea7-99234fe746fc)

**Comment by Healix** [comment]
It's not actually using that. When localized execution is set to full, each account is given its own copy of the Guild Wars 2 folder. These folders link back to the main folder, which Windows doesn't make you aware of. If you delete them, you'll notice the disk usage doesn't change.

If you were to copy the folder however, the links become real files, so never copy the Gw2Launcher folder.

**Comment by z-z00** [comment]
Sorry. I took a look and think I understand now. Thank you for your time!
