### ISSUE TITLE
Max Accounts

### ISSUE THREAD

**Issue by Cowseer** [Healix/Gw2Launcher#389]
Hello Healix, I was just experimenting and the maximum number of accounts that I was successfully able to add is 476, is that the max-limit or am I doing something wrong? Thank you

**Comment by Healix** [comment]
There's a height limitation, so after a certain height is reached, it'll just stop showing accounts. Make it wider to display more columns and you'll be able to see more.

The maximum limit is 65535. After that the account IDs will roll over to 0 and cause problems.
