### ISSUE TITLE
Reshade compatibility?

### ISSUE THREAD

**Issue by stevedwray** [Healix/Gw2Launcher#391]
I have Reshade installed in my main GW2 install, outside of Gw2Launcher, and find that it has copied the appropriate files and made a link to the folder containing the scripts.
When I run GW2 through the launcher, Reshade works in as much as home brings up its menu.
But it can't find the scripts.
I tried copying the Reshade folder 'reshade-shaders' into the launchers folder, instead of the link, and this didn't work.
When I go to the settings of Reshade, I can see the folder path when I configure it, I can see all the files, but it doesn't want to load them.

At this stage not sure if its a Reshade question or a GW2Launcher question.
Thanks

**Comment by Healix** [comment]
Gw2Laucher won't automatically copy the ini files in the main GW2 folder, which will cause reshade to load with empty settings. Copy these files (ReShade.ini, ReShadePreset.ini) to the Gw2Launcher\\# folders to prevent that. If you go under reshade's settings to manually configure the paths, note you have to click reload for it to actually find the files.

(I tried a default install of ReShade and can confirm it works on multiple accounts, with or without localized execution enabled)

**Comment by stevedwray** [comment]
Ok that does work.
What I'd done is, first time I started GW2 from the launcher, and it hadn't found the addons, I'd gone into its settings and explicitly set the path through its UI. Apparently, this created a path that it didn't like, so when I copied the ini files, it still couldn't find them.
Resetting that path, in the ini file, to the default value made it start working.
