### ISSUE TITLE
10/30/2018 Patch Broke Launcher

### ISSUE THREAD

**Issue by jalari06** [Healix/Gw2Launcher#4]
I am not sure if I am the only one but after the GW2 patch today, the launcher no longer works. It just loads up into a black or white screen and the game wont fully open.

**Comment by Healix** [comment]
The patch today broke the -email -password -nopatchui options. It may just be a bug they've introduced with the patch, or maybe they've finally disabled or updated it. I can only wait for their response on it.

**Comment by jalari06** [comment]
CRAP! I was going to make shortcuts to cover that so I could at least get my daily login rewards on all 12 accounts lol... Guess that wont work either if the command line options are broken...guess I have to type them in manually till they fix it.

**Comment by Healix** [comment]
They've fixed the problem in the last patch.
