### ISSUE TITLE
New "hamburger" menu obscured when "always on top"

### ISSUE THREAD

**Issue by xvwyh** [Healix/Gw2Launcher#40]
The new hamburger menu added in a recent (?) UI update ends up being obscured by the main window if "Show on top of other windows" is enabled. That option should be applied to the menu popup as well, "on top" windows have their own ordering, so once the popup is given focus - it will appear in front of the main window.
![image](https://user-images.githubusercontent.com/43143822/100615381-3076e380-3320-11eb-88a2-0d73fb8b08fe.png)

**Comment by Healix** [comment]
Should be fixed in the beta version:
https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe

**Comment by xvwyh** [comment]
It is, thank you.
