### ISSUE TITLE
Addons included in all accounts even though excluded in settings

### ISSUE THREAD

**Issue by Aetavicus** [Healix/Gw2Launcher#402]
I am able to use GW2Radial in all my accounts even though I had set the launcher to exclude addons and only included my main in Localized Execution.

**Current Management Settings:**
- **Mode**: Virtual
- **Enable Localized Execution**: Checked
- **Exclude Addons When Generating Folders**: Checked
- **Desired Level:** Full
- **Synchronizing**: Core
- **Accounts**: Include (Only my Main)

**Current Addons:**
- GW2Radial (Installed through GW2 Addon Manager)

**Current Accounts:**
- Main
- Alt 1
- Alt 2
- Alt 3
- Alt 4
- Alt 5

Additionally, I noticed that I am not getting any folders generated in my GW2Launcher folder when launching my accounts. There's only Gw2Launcher.exe in there. Hidden items display is enabled.

**Comment by Healix** [comment]
The Gw2Launcher folder used for localized execution is located where GW2 is. It'll be created after launching an account that uses localized execution, which would only be your main account. Inside the folder will be a # folder for the account, which will appear to be a copy of the main GW2 folder that the account will use. Treat the # folder as the main GW2 folder for the account.

All of your other accounts are excluded from using localized execution, so they're going to use the main GW2 folder and load any addons you have there. If you only want addons on your main account, remove the addons from the main folder and only place them in the # folder.

**Comment by Aetavicus** [comment]
![image](https://github.com/Healix/Gw2Launcher/assets/17705601/e08e5cf1-3a88-4bf4-a1f1-690d77fd4f02)
![image](https://github.com/Healix/Gw2Launcher/assets/17705601/a332e6c6-84d0-47a0-b40f-14d2e2cef79b)

Is this the folder you meant? As mentioned, it only has the executable within it even though I had launched my Main account multiple times. I even switched to including all accounts with localized execution and didn't see any generated folders in this location. Is there something wrong with the location that prevents folders from being generated perhaps?

**Comment by Healix** [comment]
It would prevent launching and show an error if it couldn't create the folder. For it to do nothing implies localized execution isn't being used for the account.

Assuming that is the Gw2-64.exe you told Gw2Launcher to use, that would be the correct folder. Normally Gw2Launcher would create that folder when localized execution is used and delete it when it's disabled, but you happened to create it yourself first, which shouldn't be a problem.

Open Settings > Guild Wars 2 > Management
- If the Gw2Launcher folder exists, there will be a link to open the folder next to the option to enable localized execution 
- It'll show how many accounts have been selected next to the link to select which accounts to include/exclude - confirm it's what you expect

If everything looks correct and it's still not working, use the [beta version](https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe). Right click any account > Tools > Log, then launch the account. If the account uses localized execution, the log will show it along with any potential hidden errors.

**Comment by Aetavicus** [comment]
The beta version seems to have resolved this issue. Can now see folders being generated when I launch localized accounts.
