### ISSUE TITLE
Stuck on updating Local.dat

### ISSUE THREAD

**Issue by eric-boone** [Healix/Gw2Launcher#403]
When I start the app the "Local.dat needs to be updated" window pops up and I click yes. Then a GW2 window pops up and tries to download something, then closes. GW2Launcher gets stuck trying to update the 1st account. After some time the warning about aborting shows up.

I can still launch the game with the default client.

How can I fix this?

**Comment by Healix** [comment]
GW2 currently has a problem where its process can remain active after GW2 closes. Updating waits for the process to exit, which is why it gets stuck.

When this happens, use the task manager to end GW2, or press WindowsKey+R and open: 

taskkill /IM Gw2-64.exe /F

**Comment by eric-boone** [comment]
thanks!
