### ISSUE TITLE
can only launcher 1 client 

### ISSUE THREAD

**Issue by AsheX1** [Healix/Gw2Launcher#405]
just as title says left click opens 1 client to change settings 

but i use middel click to open multi clients problem is i click the first one it starts opening and then nothing happens for any other client and gw2launcher just says w8ting on all the accounts i clicked on

**Comment by Healix** [comment]
"Launch (normal)" launches GW2 as it normally would, which is limited to 1 active account. "Launch" launches GW2 in shared/read-only mode, allowing multiple clients. You can't use both at the same time.

**Comment by AsheX1** [comment]
> "Launch (normal)" launches GW2 as it normally would, which is limited to 1 active account. "Launch" launches GW2 in shared/read-only mode, allowing multiple clients. You can't use both at the same time.

I KNOW THAT! read my text again its not doing anything wen i launch in read only 1 client starts the second never does anything

**Comment by AsheX1** [comment]
i looked at my keybindning for launching again it was set as
left click launcher normal 
and middle click launch

so middle click is launching  in read-only mode its only launching 1 any other account i middle click on just shows waiting

**Comment by AsheX1** [comment]
oke put them all to none pressed ok closed gw2launcher
re-open gw2laucnher and set them again to left click launch normal and middle click launch 

AND NOW its working what the hell

dont know what changed as this is how i set it up before and have not played for a few months only big thing that chanced on my system was that i updated from windows 11 22h3 or what ever version i was on it was 2022 version to 23h2
