### ISSUE TITLE
Multiple accounts cant be updated all together( green bar widnow gets stuck) 

### ISSUE THREAD

**Issue by Sharkinpajamas** [Healix/Gw2Launcher#406]
Hi, i have 2 pcs, in one of them the updates run smooth and no problem, the other one the last 2 weeks started to have problem with updating the games. I select all, right click, update, it opens the launcher white window saying updating, then gw2 window opens and downloads the update , then normally it should progress the green bar and apply to the rest of the accounts and all done but instead it stuck there saying "warning there have been no changes for over a minute etc etc" 

I notice when "select all" it updates only the first account that hasnt been updated and when i do it 1 by 1  (right click update) even if it stucks on the box after the download and i abort, it looks update has been applied and the next time i launch that account can start normally, i tried to delete cache, all the files from the program redownload and also import both accounts info and settings backup from the pc that its working (included .dat file) but no success, the only easy solution i found is to update all from the pc that works,then export the info transfer the file to the other pc and import, else i have to do them 1 by 1 and abort when it gets stack. 
 
 Do you have any information if i can fix this issue?

**Comment by Healix** [comment]
GW2 has had a problem for a few weeks now where its process can remain after GW2 visually closes. This causes Gw2Launcher to get stuck while updating because it's waiting for GW2 to exit.

When this happens, open the task manager (ctrl+shift+esc) and end GW2's process to allow it to continue. Alternatively, WindowsKey+R and open:

taskkill /IM Gw2-64.exe /F

**Comment by Sharkinpajamas** [comment]
Awesome, thanks so much for the info! and thanks so much for your work !!
