### ISSUE TITLE
Can't Update Guild Wars 2

### ISSUE THREAD

**Issue by Parqador** [Healix/Gw2Launcher#409]
Hey there :)
Kind of a strange issue and i can't really wrap my head around where it comes from. Ill try to describe it as precisely as possible. This is happening like this since the last two months or so.

When Guild Wars 2 has a new patch up, Gw2 Launcher wants to update automatically when i click on one of the accounts (which has always been this way and is good for me). The green update bar fills then about 30% and stays still, nothing happens anymore. There is also no Guild Wars2 window open that shows its updating. But when i check on taskmanager it shows a Guild Wars 2 instance which is using 11% of my CPU. Nothing happens from there on if I let it run this way. It doesnt update, it doesnt start, nothing. Update bar stays at 30%. Then i have to shutdown the idling GW2 instance in the taskmanager, progress bar advances a little, new instance pops up, i kill it, a little progress. After 3 or 4 times doing this it maybe works. But sometimes i also have to close everything and Update GW2 in its own Launcher and after this i can switch to Gw2Launcher. Then it seems to start. 

What i dont get is how it went from working normally to this update-procedure and my weekly tête à tête with the taskmanager. Can you perhaps help me out on this one? Should i reinstall Guild Wars2?

Any help is appreciated! 
~Parq

**Comment by Healix** [comment]
GW2 started having this problem with the patch in January. It causes GW2's process to remain active after GW2 visually exits, preventing further launches. Gw2Launcher waits for the process to exit when updating, which is why it gets stuck. Kill Gw2-64.exe in the task manager for it to continue.

To lessen this problem, Settings > Tools > Local.dat > Allow directly updating Local.dat, then only 1 account has to be updated and the rest are copied.

**Comment by Scruffy-Scruffy** [comment]
I've had trouble for 2 days (since the patch) as well. 

If I try to launch either of my 2 accounts, the launcher tries some downloaded but then fails with an error message in red text; "Download failed! Please check your internet connection and try again. (5)"

**Comment by Healix** [comment]
"Download failed!" is when the game is partially updated. Right click any account > All > Update.

**Comment by Scruffy-Scruffy** [comment]
Thanks so much. Account > All > Update made it work. Cheers!

**Comment by Parqador** [comment]
Thanks a lot for your insanely fast reply! I tried it and it did work. You've made my life so much easier again, thank you :)

Threas closed.
