### ISSUE TITLE
Launcher no longer opens using the -update shortcut command

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [Healix/Gw2Launcher#41]
No window appears or anything.

Before it would show progress of each .dat file being updated 1 after the other.

**Comment by SaiyanOfDarkness** [comment]
Thankfully I still had a backup version (btw it's not good to remove previous versions in case current ones break for people).

**Comment by Healix** [comment]
Should be fixed in the beta version:
https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe

Old versions can be found through the history:
https://github.com/Healix/Gw2Launcher/commits/master/Gw2Launcher/bin64/Release
