### ISSUE TITLE
How to mass change password on all accounts

### ISSUE THREAD

**Issue by ChoriSw** [Healix/Gw2Launcher#412]
For some reason all my passwords got deleted(something to do with my PC) and for some accounts i had the same password, is there a way to changethe mass-change the password on those accounts?

**Comment by Healix** [comment]
No, there's no easy way to change only the password for multiple accounts. The email and password are currently linked, so it would change both.

**Comment by ChoriSw** [comment]
Damn, thanks for letting me know!
