### ISSUE TITLE
Manually rearrange the account list / Pin Accounts

### ISSUE THREAD

**Issue by AnimaCaniba** [Healix/Gw2Launcher#42]
I have two suggestions I would like implemented or if they already are know where to locate the options. Both pertain the Launcher account list.

I see the 'Sort By' option when right clicking but none of those options do what I want and the custom section is quite limited.

First is manually rearrange accounts on the Launcher menu list:

If I add 3 accounts, but want to change the order later I would like a click & drag feature, if possible, to raise/lower the specific account.

For example:

Account 1

Account 2

Account 3 

I click & drag Account 2 down so now it shows

Account 1

Account 3

Account 2

-------

The other feature I would like to see is a pin account option, in other words a method to prevent each account(s) to be sorted if you so choose. The same feature you see on Twitter where a pinned Tweet is always at the top on that person's page.

So if I have: 

Account 1 (Pinned)

Account 2

Account 3

Account 4

and I pin Account 1, if I do 'Sort by X' it will sort all non-pinned accounts.

I would like to keep my main account at the very top without ever having it be sorted or moved. Also an indication that it is pinned too if possible. 

On top of that if for whatever reason I need to delete an account and add it back later, since the program places it at the bottom of the list, I would just like to click & drag it back to its original spot.

**Comment by Healix** [comment]
"Sort by > Custom" allows you to drag accounts to manually sort them. You can drop an account between accounts, or drop it onto another account to swap them.

**Comment by AnimaCaniba** [comment]
Oh, awesome, not sure how I missed that when looking. much appreciated and love the program, keep it up.

**Comment by Healix** [comment]
Pinning is added to the beta version:
https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe

You can find it under right click > selected > pin to top.

**Comment by AnimaCaniba** [comment]
Awesome, works like a charm, thank you!
