### ISSUE TITLE
Disable ArcDPS

### ISSUE THREAD

**Issue by artur-rafael** [Healix/Gw2Launcher#425]
Hello,

I use ArcDPS on GW2 but I would like to disable it when launching my accounts using Gw2Launcher. How can I achieve this?

Thanks in advance.

**Comment by Healix** [comment]
The simplest option is just renaming d3d11.dll (and/or dxgi.dll, whichever you're using) on launch. You'll need to use a batch script when launching the game outside of Gw2Launcher.

Save the following script as Gw2-64.bat in the same folder as Gw2-64.exe:

move d3d11.dll.x d3d11.dll
start Gw2-64.exe %*

In Gw2Launcher, add a script to run before launching (Settings > Guild Wars 2 > Launch options > Run after launching > Shell commands):

move "c:\path\to\Guild Wars 2\d3d11.dll" "c:\path\to\Guild Wars 2\d3d11.dll.x"

---

The other way is using localized execution, which gives each account its own GW2 folder - note these folders will appear to take up a lot of space, but they actually don't.

Settings > Guild Wars 2 > Management > Localized execution > Enable, Exclude addons, Full.

**Comment by artur-rafael** [comment]
Thanks a lot for the detailed explication!
