### ISSUE TITLE
settings menu remains behind the main app

### ISSUE THREAD

**Issue by gunnho** [Healix/Gw2Launcher#43]
i cannot select the app settings menu when clicking the 3 horizontal bars in the top left corner of the app, when clicking them the settings popup menu pops behind the app as the app is set to always be on top. 

i can of course still select each account and access their popup menu to "edit "each account setting and there i can access the app settings. so i am only missing out on the app "search" and "page <>" selections

this has occurred since the last update.

edit, now that i turned "show on top of other windows" off and on again, the search and page popup is now correctly on top

**Comment by Healix** [comment]
This is fixed in the beta version:
https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe
