### ISSUE TITLE
both e-mail and password are input in the password field 

### ISSUE THREAD

**Issue by Latakerni** [Healix/Gw2Launcher#431]
As in the title, both email and password are set in the same field, preventing login

![Capture](https://github.com/user-attachments/assets/949a3d47-8391-46af-ae32-d9206678c563)

**Comment by SaiyanOfDarkness** [comment]
Getting same problem, but if you are also use the 👍

**Comment by sciandapol** [comment]
Yes, I have the same issue...

**Comment by Chaoticity** [comment]
There's already a working beta https://github.com/Healix/Gw2Launcher/blob/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe

**Comment by Master-Liu-TBF** [comment]
i came here to report the same issue.

**Comment by Healix** [comment]
There was a minor change in the field order for the new launcher. Use the beta version if you were, whereas the new release version is the old release + this one fix.

**Comment by michisure** [comment]
the same issue her ;(

**Comment by Wolfoly** [comment]
working fine with the beta, thx

**Comment by Latakerni** [comment]
yeah, beta version works, closing
