### ISSUE TITLE
Graphics Settings persisting accross multiple local.dat files

### ISSUE THREAD

**Issue by luigiormario7** [Healix/Gw2Launcher#440]
Hi, 

Apologies if this has already been covered somewhere but I am trying to have independent graphical settings (i.e. window vs fullscreen, high vs low quality) across a number of accounts. However despite running Launch (normal) on these accounts to change the local.dat settings, the graphics settings seem to persist across all accounts from any change, despite other changes such as sound being retained for individual accounts. 

This also seems to be the case under Edit > Local.dat > Graphics, where changes can be made but seem to apply to all accounts. Please tell me I'm missing something obvious - I have also tried creating a new local.dat file which didn't seem to help in this.

**Comment by Healix** [comment]
GFXSettings.xml is what controls most graphics settings. Edit > Local.dat > Graphics. Ensure the accounts aren't sharing the same file.

**Comment by luigiormario7** [comment]
Thankyou very much, that did the trick!
