### ISSUE TITLE
GW2 /wiki chat command not working with Firefox due to GW2Launcher not linking to the original browser profile

### ISSUE THREAD

**Issue by MajesticPeter** [Healix/Gw2Launcher#446]
Firefox won't open wiki links because GW2Launcher isn't linking to the default Firefox profile in its appdata folder and instead copies it for each GW2Launcher account profile. 

A soft error pops up saying: 
"Firefox is already running, but is not responding. The old Firefox process must be closed to open a new window." 
The popup has 2 options; "Close Firefox" and "Cancel". If you press "Close Firefox", Firefox will reopen with the Firefox profile stored in **%appdata%\Gw2Launcher\data\(account profile #)\AppData\Roaming\Mozilla\Firefox\Profiles** folder and open the /wiki link. However this breaks all external hyperlinks for Firefox now because the original default profile isn't loaded anymore. By default, Firefox stores profiles in **%appdata%\Mozilla\Firefox\Profiles**. Wiki chat commands open links in Firefox normally as expected when GW2 is launched normally and not through GW2Launcher.

How to replicate:
- install latest version of Firefox 131.0.3 64-bit 
- set Firefox as the default Windows browser 
- open Firefox and Enter URL **about:profiles** to check and ensure there is only one default profile (take note of the location of the profile) 
- keep Firefox open and launch GW2 via GW2Launcher, login to a character and use the ingame /wiki chat command 
- Firefox will take a second and then open the prompt. Press "Close Firefox" (it should reopen Firefox with the /wiki link) 
- check **about:profiles** again. The location of the profile should change to the one stored in GW2Launcher folder 
- click any hyperlink in any external application (eg.: Steam, Discord etc.) and you'll get the same prompt which if you choose to Close Firefox again, will switch back to the original default profile. It basically becomes a loop of which profile is loaded into Firefox 

Workaround: 
downgrade Firefox to version 124.0 or older

Request:
Can you please update GW2Launcher to use the original Firefox profile instead of copying it to prevent this needless profile switching.

**Comment by Healix** [comment]
It's a side effect of using virtual mode, which causes GW2 to use a different %appdata% folder so it doesn't interfere with the original. Problem is, anything started by GW2 will end up using the same folder.

To avoid this, you have to use basic mode under Settings > Guild Wars 2 > Management.

**Comment by MajesticPeter** [comment]
> It's a side effect of using virtual mode, which causes GW2 to use a different %appdata% folder so it doesn't interfere with the original. Problem is, anything started by GW2 will end up using the same folder.
> 
> To avoid this, you have to use basic mode under Settings > Guild Wars 2 > Management.

That works. Thanks
