### ISSUE TITLE
Usage of the Local.dat

### ISSUE THREAD

**Issue by Caliban2017** [Healix/Gw2Launcher#447]
Hello again,

i have a Question regarding the usage of the Local.dat and Graphics.xml File. In the past i had some issues, where all my Accounts from GW2Launcher used the same Local.dat File as my Main Account, which i do not use in GW2Launcher. The issue was that it automatically overwrited the Login-Data in the Launcher from the Main Account, so when i started GW2 manually, i had to enter again the credentials from my Main Account.

My Plan is now: one Local.dat for my Main Account, which stay untouched and one for my GW2 Launcher Accounts. All the Accounts should share one File to save Disk space. But i don't understand, how i manage the Local.dat File.

When i try to edit the Local.dat Path, it is not manually possible. I have to use the Window, where i can choose from which account the Local.dat should be used or copied from. But i can not set an own Path for it. When i try to create a new one, it always points to a .tmp File in the Temp Folder. 

Isn't it just possible to manually browse for a Local.dat File. So as example, create one new File in the Gw2 Folder, Multiple Edit all accounts and browse for that File, now confirm it and all accounts use this specific file?

Thank you very much for any Help!

Greetings,Caliban

**Comment by Healix** [comment]
You can use an existing file, but you can't specify where to keep it. Files will always be moved under Gw2Launcher. It's a limitation to not require running Gw2Launcher as an administrator.

To use an existing file, you choose the option to copy/move an existing file. It'll use the temp folder for any new Local.dat file because it's not confirmed yet. Once you click OK, it'll be moved under Gw2Launcher.

**Comment by Caliban2017** [comment]
Got it, thank you for the explanation. I deleted all files now, created with the first Account with ID1 a new Local.dat, then selected all other Accounts and choosed Share with Account 1 and now all are using the File of Account 1, which will hopefully exactly do, what i wanted.
