### ISSUE TITLE
random shutdown 

### ISSUE THREAD

**Issue by jor8888** [Healix/Gw2Launcher#45]
Assertion: Failed to start Coherent host 
File: ..\..\..\Engine\ArenaWeb\CoherentUi\AwCohContext.cpp(332)

**Comment by Healix** [comment]
CoherentUI is used by the launcher and BLTC. The game will temporarily lock access to it while initializing, which causes any other accounts that also want it in that moment to fail. To prevent this...

Right click any account > Settings > Guild Wars 2 > Management > Localized CoherentUI

Enable giving each account its own instance of CoherentUI.

**Comment by jor8888** [comment]
k
