### ISSUE TITLE
can no longer launch multiple accounts at the same time

### ISSUE THREAD

**Issue by jdes375** [Healix/Gw2Launcher#46]
I can only launch one account at a time now, I'm not sure what changed. I only added an additional account recently and the issues started then. I get the GW2 error "Install cannot be completed. Please contact Support" 
There are no issues launching each account by itself.

**Comment by Healix** [comment]
There are few potentials that could cause it. I'm assuming you're using the latest version of Gw2Launcher.

If GW2 is installed under Program Files, it may require being ran as an administrator, which requires starting Gw2Launcher as an administrator (right click the exe > run as admin).

GW2 has some quirks to how it handles its bin folder. In Gw2Launcher, right click any account > Settings > Guild Wars 2 > Management. "Localized CoherentUI" is essentially required to run multiple accounts. "Localized Execution" takes it a step further. Also try changing the mode (virtual, basic), which will trigger checks on your next launch when no accounts are active.

Addons / DLLs you put in the bin64 folder can cause this error. You can use "Localized Execution" mentioned above to give each account its own bin folder. To first verify if this is a problem, simply delete (or rename) the bin64 folder, and if you were using localized execution, the Gw2Launcher folder in the same folder as bin64.

**Comment by jdes375** [comment]
> There are few potentials that could cause it. I'm assuming you're using the latest version of Gw2Launcher.
> 
> If GW2 is installed under Program Files, it may require being ran as an administrator, which requires starting Gw2Launcher as an administrator (right click the exe > run as admin).
> 
> GW2 has some quirks to how it handles its bin folder. In Gw2Launcher, right click any account > Settings > Guild Wars 2 > Management. "Localized CoherentUI" is essentially required to run multiple accounts. "Localized Execution" takes it a step further. Also try changing the mode (virtual, basic), which will trigger checks on your next launch when no accounts are active.
> 
> Addons / DLLs you put in the bin64 folder can cause this error. You can use "Localized Execution" mentioned above to give each account its own bin folder. To first verify if this is a problem, simply delete (or rename) the bin64 folder, and if you were using localized execution, the Gw2Launcher folder in the same folder as bin64.

So, I ran the exe as admin, issue was not resolved.

I then made sure "Localized CoherentUI" was enabled (along with localized execution, which was on by default), issue still persisted.

Finally, I deleted bin64 which made it work again! 

Thank you for the help Healix!
