### ISSUE TITLE
Issues to load TaCo addon 

### ISSUE THREAD

**Issue by pjllorens** [Healix/Gw2Launcher#53]
Issues to load TaCo addon. After launching, for example two accounts, when running TaCo it will behave appearing a disappearing in both instances. Tried to add TaCo.exe in launching options in one of the accounts, but I'm experiencing the same behavior.

**Comment by pjllorens** [comment]
Just found another issue reported about TaCo

**Comment by Healix** [comment]
By default, GW2's public memory is named MumbleLink, which is where programs like TacO get its positional data from. When all accounts are using the same name, they will overwrite each other. About a year ago, GW2 added support for running multiple clients.

To change the name in Gw2Launcher (for all accounts):
Settings > Guild Wars 2 > Launch options > Mumble link name

By default, it's:
MumbleLink_%accountid%

You then pass it to TacO with the option:
-mumble MumbleLink_%accountid%
