### ISSUE TITLE
Blank right click window in WINE.

### ISSUE THREAD

**Issue by Rojikku** [Healix/Gw2Launcher#55]
Greetings! Thanks for developing this. I play through wine, using ArmoredVehicle's build- so running on Linux, if you're unfamiliar with wine. It works with the exception of a couple key features.

Since there's only a couple bugs when using it through wine, I thought I'd ask if you were interested in trying to fix them.

What works:
Most things, honestly.
Settings seem fine.
I setup an account and launch it fine.
I assume more accounts would also work fine, but I haven't purchased more yet.

What does not:
Bigges concern, the right click menu.
![image](https://user-images.githubusercontent.com/1676068/119894501-aee8c280-bf0a-11eb-848e-ed17e8f76073.png)
It WORKS, don't get me wrong. I'm just not quite daring enough to randomly click options I can't read. I tried adjusting the color scheme, no dice. When I pop up other menus those work.

Also it lists as "never" under the account name, for which I assume is login period. But I have logged in not only previously, but today, moments ago. I even added the API key. So there might be issues with that running through wine as well. That or I have it setup wrong. Which I can't really investigate because my right click doesn't work appropriately.

---

Perfectly happy to test and run test builds, if you give me some vague compilation instructions.

**Comment by Healix** [comment]
It looks like you're using Mono, which is what Wine will ask to install by default when you try to run a .NET application. Mono has rendering problems, which is what's causing the white menu, lack of text color and the white background on "Launcher" for example. If you remove Mono (wine uninstaller) and install the actual .NET 4.5 Framework from Microsoft, it won't have this problem (use Windows 7 compatibility and native mscoree under winecfg - tested on Wine 5.7).

As for "never", it should display the last time the game was played (to character select). If it doesn't change, then Gw2Launcher isn't able to detect the game's window. I'll assume it's broken (last tested over a year ago on Wine 5).

**Comment by Rojikku** [comment]
That fixes it dead on! That also fixed the "never" under the account name, the API keys now work, and all sorts of goodies.

I bought a second account, and my only remaining issue is that the saved credentials are exactly the same between the two logins. If I just logout and login and save, the other is also effected by this. Am I doing it incorrectly?

Also I'd love to copy my settings from my main account when I make new accounts- namely keybinds. Is there a good way to do that? They share graphics settings already and that appears to work perfectly.

**Comment by Healix** [comment]
The way Local.dat files are handled by default isn't working under Wine, which causes all accounts to use the default Local.dat and GFXSettings.xml regardless of what was chosen. To get around that, change the mode to basic under Settings > Guild Wars 2 > Management. 

GW2 stores its hardware-related settings (graphics, sound and login) in Local.dat. Everything else is stored by the server itself, which can't be copied between accounts.

Launching multiple accounts at a time isn't working depending on the version of Wine used.

**Comment by Rojikku** [comment]
Ah! Setting the mode to basic made everything work perfectly (After getting new Local.dat files), thanks!
