### ISSUE TITLE
Double addon

### ISSUE THREAD

**Issue by Vatroki** [Healix/Gw2Launcher#56]
For some reason when i start the game with addons they show as double. 
![Gw2-64_WA37tTJGaf](https://user-images.githubusercontent.com/66736859/119975158-cb8e0480-bfb5-11eb-9eef-248a6ee07a98.png)

**Comment by Vatroki** [comment]
I only have 1 of each file. Regular stuff in the bin64 : 
![explorer_2QNEf3voNn](https://user-images.githubusercontent.com/66736859/119996618-37c93200-bfcf-11eb-8489-30fb0ffb9d53.png)

And this is how the folder looks that the Gw2Launcher made: 
![explorer_6i2laNr5oP](https://user-images.githubusercontent.com/66736859/119996694-49123e80-bfcf-11eb-874e-e9326aa34d58.png)

If i start the game from the normal launcher it doesn't show the double addons, if u use the Gw2Launcher it shows it double even tho in the folder there's only 1 dll each.

**Comment by Healix** [comment]
What's happening is arc is loading the addons (table/killproof) from the default bin64 folder and the Gw2Launcher folder. You have to remove one or the other.

Alternatively, localized execution to "full" won't have this problem.

**Comment by Vatroki** [comment]
Alright, deleting it from the launcher folder worked for me. Thank u :)
