### ISSUE TITLE
Cant run multple Clients

### ISSUE THREAD

**Issue by sm0uz** [Healix/Gw2Launcher#60]
Hi Healix. 
Im pretty new to the multi-account-"scene" - first off: big thanks for this great tool! :-)

sadly, im running into an issue since yesterday. Im using the Program 3 days now and everything worked fine so far until yesterday. There was a little Patch when i was running my Clients - nothing big. 

but since then, im only can open up 1 client at the time - i dont got any error's or something. i tried opening the client 1by1 and every 5 clients fast together, same issue.

gw2launcher telling me "active" but there doesnt showing up the client. As example: im running Client1 & Client2 at the same time, client 1 shows up and everything is fine - 2nd wont. When im closing the Client1, the client2 "begins" to load and showing up like 20seconds after.

already tried many of the other issue-resonse here, nothing seems to work. Tried to change the Settings>GW2>Managment-Stuff and updated every client with "update all" - was deleting the cache and gw2launcher folder in gw2 - still not working. 
I tried normal and beta version :/

Any idea's? Thanks!

**Comment by sm0uz** [comment]
update: got it working again. since i've read some issues with addons, i was going to "Settings>GW2>Managment" and used "Exclude addons when generating folders" and used "full" and "core" - working now! (i re-synced the localized execution" !

thanks!

**Comment by Healix** [comment]
This is caused by d912pxy - it will prevent the game from loading while its file in are in use. Setting "localized execution" to "full" is required if you want to use d912pxy on multiple accounts.
