### ISSUE TITLE
Graphics settings keep resetting on every launch

### ISSUE THREAD

**Issue by IronMonkeyL255** [Healix/Gw2Launcher#68]
I have tried changing the settings in game, but the settings are always changed to be way too high for my system on next login. I tried manually changing the gfxsettings.xml files by editing the 1.xml that is linked to both 'gfxsettings.xml's (and confirmed that everything is how I want it), but it gets changed as soon as I launch to the same inappropriate settings.

The wiki says to choose which gfxsettings.xml to use in the local.dat menu in settings, but the only option there are 'Faster Local.dat Patching' and 'Static Cache Location', both of which are checkboxes and do not reflect what is being referred to in the wiki.

**Comment by Healix** [comment]
The Local.dat section you're wanting is under the account's settings: right click the account > Edit > Local.dat > Graphics.

GW2 will be in read-only mode when launched, which prevents it from modifying its local settings, with the exception of most graphics settings. If you want to be able to change settings in-game, you need to launch the account by right clicking it > Selected > Launch (normal). If you were trying to change the graphics settings while multiple accounts were running, they would overwrite each other if they were sharing the same file.

**Comment by IronMonkeyL255** [comment]
Thank you for your prompt reply. I had tried right clicking, but only thought to check 'settings', which brought up the same settings page as clicking the menu button.

**Comment by IronMonkeyL255** [comment]
I just tried the correct menu, but changing the setting in this menu still results in the game launching with the incorrect settings. I tried telling it to copy the 64 bit GFXSettings from the regular game settings and everything looked good, but it still reverts when I launch the game. Though I believe I just found that launching GW2Launcher as administrator allows things to work as intended.
