### ISSUE TITLE
How can I launch the game in Borderless Fullscreen

### ISSUE THREAD

**Issue by Abbyfa** [Healix/Gw2Launcher#69]
Hey, so normally when I change the graphic settings and leave, they are saved. Things like Texture, Animation, and Reflections etc
But no matter how many times I switch to Windowed Fullscreen it always loads again in normal Fullscreen.
I tried editing the GFXSettings.Gw2 files found in "%APPDATA%\Guild Wars 2\" but they don't have the option to change Display Resolution.
I tried launching the game with some line arguments like "-windowed" but it makes the game such a small window and not Windowed Fullscreen. What am I missing?
One more thing that doesn't seem to save is sound settings.
Any suggestions?

**Comment by Healix** [comment]
GW2 is will not save your "local" settings (sound, some graphics and the stored login) when it allows multiple clients to be started, If you want to change something, you have to launch GW2 by right clicking the account > Selected > Launch (normal).

If you want to edit GFXSettings.xml, right click the account > Edit > Local.dat > Graphics.

**Comment by Abbyfa** [comment]
Thank you very much!
