### ISSUE TITLE
Resets Directx 11 setting

### ISSUE THREAD

**Issue by TaygaHoshi** [Healix/Gw2Launcher#70]
When logged in normally, official launcher keeps the checkbox for Directx 11 beta. When launched from this however, it resets to unchecked.

**Comment by Healix** [comment]
GW2 is in read-only mode when it allows multiple clients to launch. If you want to modify a setting like this, you have to right click the account > Selected > Launch (normal). Note it'll also be reset by GW2 if you choose autodetect for your graphics.

Alternatively, just use the -dx11 argument, which you can set per account under Edit > Launch options, or globally under Settings > Guild Wars 2 > Launch options. Note this option forces GW2 to use DX11 (the option won't be checked). Similarily, -dx9 forces DX9.

That said, DX11 isn't supported yet - expect accounts using windowed options to not have those options applied. I'll have a fix for that soon (it's just a name change).

**Comment by TaygaHoshi** [comment]
I see. Thanks for quick response, I didn't know there was a Launch (normal) option.
