### ISSUE TITLE
DX11

### ISSUE THREAD

**Issue by Spughety** [Healix/Gw2Launcher#71]
I saw you posted an update on the 21st to support DX11. I installed the update but I don't see the DX11 checkbox in the Graphics settings.

**Comment by Healix** [comment]
The last update only fixed accounts using DX11. The DX11 client uses a different name for its window, so it broke any window-related options.

If you want to enable DX11, simply add -dx11 to the launch options / arguments. This forces GW2 to use DX11 (note the box will remain unchecked in the game).
