### ISSUE TITLE
Won´t save GW2 Path after relaunch

### ISSUE THREAD

**Issue by Xevius95** [Healix/Gw2Launcher#79]
After a Restart the Launcher wont launch any GW2 Account.

Failed -> "
The object reference was not set to an object instance"

When i set the Path to Gw2-64.exe again it works until i close the Launcher again.
Gw1 works just fine.

Path Gw2: C:\Program Files\Guild Wars 2\Gw2-64.exe
Path Gw1: C:\Program Files\GUILD WARS\Gw.exe

![Screenshot 2021-10-16 230754](https://user-images.githubusercontent.com/92651197/137602123-b9793c62-9f80-46d3-8d5a-b6f8b7d49e9a.png)

thx for your awesome Work :)

**Comment by Healix** [comment]
How is the path not saved? Is it blank after restarting Gw2Launcher?

Restart Gw2Launcher, open the settings and click OK without changing anything, then try to launch an account. Is it still causing the error?

Restart Gw2Launcher, add a new account and try launching it. Does it fail? Restart Gw2Launcher again. Is the account still there?

Try the beta version. It won't fix the problem, but it will hopefully give a more meaningful error:
https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe

**Comment by Xevius95** [comment]
**How is the path not saved? Is it blank after restarting Gw2Launcher?**
_- No the Path is still set_

**Restart Gw2Launcher, open the settings and click OK without changing anything, then try to launch an account. Is it still causing the error?**
_- No after just pressing OK it works fine until i restart it_

**Restart Gw2Launcher, add a new account and try launching it. Does it fail? Restart Gw2Launcher again. Is the account still there?**
_- New Account it saved correctly. Firt Launch without Problems. After restart -> Failed._

Ill try the Beta Version tomorrow and Delete the GW2Launcher Folder in %AppData% and GW2 Main Directory.

**Comment by Healix** [comment]
Just to confirm, these are all scenarios where you had just started Gw2Launcher and launching an account would fail.
- opening the settings and only clicking OK will fix it.
- adding a new account will launch - did that also fix it for other accounts?

If you edit an account and only click OK, does that also fix it?

Assuming you're using localized execution, close Gw2Launcher and delete the Gw2Launcher folder in GW2's folder. Can you launch an account? If not, disable localized execution, restart and try again.

**Comment by Xevius95** [comment]
Ok i'm confused.
After I set everything from scratch with the beta version it seems to work ...

At least I can't reproduce it anymore.

Many thanks for the support! If it should happen again, I'll get in touch.
