### ISSUE TITLE
Timer doesn't reset

### ISSUE THREAD

**Issue by Fiftymag** [Healix/Gw2Launcher#84]
Everything works fine except timer does not reset when GW2 is exited. Displays "active" when launched but icon remains and timer continues to add time after game log off.

**Comment by Healix** [comment]
The (timer) "last used" status only updates if it detects that the game was "played" (loaded to the character select). Gw2Launcher also needs to be kept running, as it only updates it when the game is exited.

Use the beta version. I've included a little logging to see what's happening. A window.log file will be created in the same folder as Gw2Launcher after exiting an account. Start 1 account and load it to the character select screen. Check the log and post it - if it doesn't exist yet, exit the game.
https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe

**Comment by Fiftymag** [comment]
It created a new launcher that appears to work perfectly for all 5 accounts. Thank you
[window.log](https://github.com/Healix/Gw2Launcher/files/7475508/window.log)

**Comment by Healix** [comment]
If that alone fixed it, the problem was most likely caused by having DX11 enabled while using the pre-DX11 version of Gw2Launcher.

You can re-download the beta version to remove logging and can delete window.log.
