### ISSUE TITLE
Running multiple accounts and Blish HUD

### ISSUE THREAD

**Issue by pjllorens** [Healix/Gw2Launcher#89]
I have three accounts added into the launcher, only one of them has "Run after launching" configured to start Blish HUD. When I run this account, Blish HUD overlay gets randomly into the other opened accounts.
I tried the option to use mumble link as it worked on TaCo, but Blish HUD doesn't recognize the parameter.
My GW2 Management config is Virtual, Localized execution, Binaries, All.

**Comment by Healix** [comment]
https://blishhud.com/docs/user/launch-options

To use the mumble option (default value: MumbleLink_%accountid%), you would launch Blish with:
-m MumbleLink_%accountid%

If you didn't want to rename the mumble link, you'd have to specify the process ID instead:
-P %processid%

**Comment by pjllorens** [comment]
Yes I figured out after posting that the parameter is with "-m" or two dash. After setting it correctly, Blish Hud accepted it.
But the overlay keeps opening in other instances. I even tried to rename the mumble link, but same results.

**Comment by pjllorens** [comment]
Ok, solved it by giving each account a unique mumble name with "MumbleLink_%accountid%".
And in the desired account only selected to launch Blish Hud with "-m MumbleLink_%accountid%"

Thank you Healix
