### ISSUE TITLE
Feature Request: Disable window shadow

### ISSUE THREAD

**Issue by xvwyh** [Healix/Gw2Launcher#96]
I'd like to request an option to disable aero-like shadows on the main GW2Launcher window, but only if it won't take you longer than 10 minutes to implement, because, frankly, it's not worth any more hassle than that.

This is no doubt a rather strange request, but I can explain.

<details>
<summary>Storytime</summary>

I just recently realized that I had been potentially gutting my gaming performance because of GW2Launcher. I used to keep the launcher on a side monitor, close to the edge of the main monitor, so it can be conveniently used to swap between active clients. And "always on top". It wasn't exactly on the edge, because I didn't want it dropping the shadow onto the games running on main monitor, but, apparently, I didn't drag it just far enough away for its shadow to *completely* stop overlapping the main monitor.

Big deal, you may say, who cares about a bit of a shadow, right? Well, as it turns out, DWM does. Through Microsoft's infinite wisdom, Windows 10 got rid of exclusive fullscreen mode entirely, it now runs all games in borderless fullscreen, whether you like it or not, and choosing the exclusive fullscreen option only makes Windows fool the game into thinking its obeying the user's choice, while in reality it keeps running the game in borderless fullscreen. Windows, however, has something called "fullscreen optimizations" - a feature in which DWM allows the game to completely bypass desktop composition and output directly to the backbuffer *if the game window completely covers the screen and isn't obscured by anything else* like overlays, gamebars and other crap. You may see now where I'm going with this. Because GW2Launcher was "always on top", it actually was overlapping any and all games that were being played in ~~exclusive~~ borderless fullscreen on my main monitor, thus preventing fullscreen optimizations from kicking in.

To make matters worse, even when I though I was in the clear, because I dragged the window far away enough for no shadow to "leak" onto the main monitor, it *still* wasn't enough, because technically window rendering boundaries extend a couple of pixels beyond the radius of the shadow. It took actual experimentation (by watching for input lag in a game) to figure out just how far the window needs to be from the monitor boundary in order for it to be considered to not overlap the other monitor.
</details>

I recognize how specific of a request this is, and how few people may be affected by this issue (and how even fewer realize they suffer from it), so please, have no second thoughts about denying it. It's not even a problem specific to GW2Launcher, literally any other "always on top" window can cause the same issue. And GW2Launcher already has sort of a solution in the form of "Account Bar" that features no shadows, but it's also a fair bit less functional than the main launcher window.

**Comment by Healix** [comment]
I've temporarily disabled shadows in the beta version:
https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe

The next build will have an option to disable shadows under settings > style.

**Comment by xvwyh** [comment]
That does the trick, thank you!

On the topic of shadow, there's one thing I've always wondered about, maybe you can satisfy my curiosity: how come GW2Launcher is the ONLY application I've ever seen to be dropping shadows on taskbar thumbnails:
![image](https://user-images.githubusercontent.com/43143822/144375613-c3d7bf01-d288-452c-a3b8-ece5e3a13dc0.png)
(screenshot of the previous version)

I've never seen this on any other window, not even Window's own windows, neither old, nor Metro-styled.

It could lead me to think that shadows are part of the client area of the window, but nope, both the notepad's and the launcher's thumbnails have the same spacing from the edge of the "peek" window, disproving that theory.

**Comment by Healix** [comment]
It is in the client area, it just continues outside of it.

**Comment by xvwyh** [comment]
Found your WindowShadow.cs, played around with that code. It almost looks like a hack that a combination of `DWMNCRP_ENABLED` and `DwmExtendFrameIntoClientArea` causes a borderless window to start dropping shadow, but only if any of the sizes passed to `DwmExtendFrameIntoClientArea` is non-zero. And not just around the window, but also on taskbar thumbnails. Interesting that taskbar takes this into account and renders the non-client-area shadow outside of the bounds reserved for thumbnail. And `DWMNCRP_DISABLED` with borders behaves just plain weird, revering to the old classic aero window theme. Regardless, a useful trick to know.
